### ISSUE TITLE
Issues with shutdown script

### ISSUE THREAD

**Issue by ferllings** [domogik/domogik#135]
$sudo domogik/domogik.repository.git/src/domogik/examples/init/domogik stop
Mot de passe [sudo] de cedric :
 * Stopping Plugins...Traceback (most recent call last):
  File "/usr/bin/dmg_send", line 9, in <module>
    load_entry_point('Domogik==0.4.0', 'console_scripts', 'dmg_send')()
  File "/home/cedric/domogik/domogik.repository.git/src/domogik/bin/send.py", line 105, in main
    Sender()
  File "/home/cedric/domogik/domogik.repository.git/src/domogik/bin/send.py", line 63, in __init__
    XplPlugin.__init__(self, name = 'send', daemonize = False, parser = parser, nohub = True)
  File "/home/cedric/domogik/domogik.repository.git/src/domogik/xpl/common/plugin.py", line 78, in __init__
    self.myxpl = Manager(self.config['bind_interface'], broadcast = broadcast, plugin = self, nohub = nohub, source = source)
  File "/home/cedric/domogik/domogik.repository.git/src/domogik/xpl/common/xplconnector.py", line 156, in __init__
    addr = addr_list[0]
IndexError: list index out of range

**Comment by ferllings** [comment]
Works when plugins are available
