### ISSUE TITLE
Error starting scenario.py with a first scenario create

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#140]
Hello

After creating/saving a scenario on Domogik 0.4.1, the admin interface don't show any create scenario.
Same error en GIT version with the same scenario:

    $ ./src/domogik/bin/version.py
    REST_API_release : 0.7
    Domogik_release : 0.4.2
    Sources_release : 0.4.2

I restart scenario.py -f with this error. scenario stay en starting mode:

    $ /opt/dmg/domogik-0.4.1/src/domogik/bin/scenario.py -f                          
    is manager
    2015-10-15 20:33:08,837 domogik-scenario INFO Looking for launched instances of 'scenario'
    2015-10-15 20:33:08,850 domogik-scenario INFO No existing process.
    2015-10-15 20:33:08,853 domogik-scenario DEBUG watcher fork
    2015-10-15 20:33:08,854 domogik-scenario INFO ----------------------------------
    2015-10-15 20:33:08,855 domogik-scenario INFO Starting client 'scenario' (new manager instance)
    2015-10-15 20:33:08,855 domogik-scenario INFO Python version is sys.version_info(major=2, minor=7, micro=9, releaselevel='final', serial=0)
    2015-10-15 20:33:08,857 domogik-scenario DEBUG Send client status : starting
    2015-10-15 20:33:08,859 domogik-scenario DEBUG Write pid file for pid '17611' in file '/var/run/domogik/scenario.pid'
    2015-10-15 20:33:08,859 domogik-scenario INFO End init of the global client part
    2015-10-15 20:33:08,859 domogik-scenario DEBUG Send client status : starting
    2015-10-15 20:33:08,862 domogik-scenario INFO Checking for MQ services : ['plugin-onewire.ares', 'butler', 'plugin-weather.ares', 'plugin-diskfree.ares', 'manager', 'admin', 'dbmgr', 'rest', 'xplgw']
    2015-10-15 20:33:08,863 domogik-scenario INFO Needed MQ services available : continuing startup
    2015-10-15 20:33:08,906 domogik-scenario INFO Create or save scenario : name = '1', id = '1', json = '{"type":"dom_condition","id":"1","IF":{"type":"logic_compare","id":"25","OP":"LTE","A":{"type":"sensor.SensorTest.68","id":"55"}},"DO":{"type":"log.LogAction","id":"12","message":"Temperature <= 0"},"deletable":false}'
    2015-10-15 20:33:08,912 domogik-scenario DEBUG Create action instance log.LogAction with uuid 6d5723cb-6228-4082-948d-b05e03d97943
    {'0-6d5723cb-6228-4082-948d-b05e03d97943': <domogik.scenario.actions.log.LogAction instance at 0x7f6f540278c0>}
    sensor.SensorTest.68
    2015-10-15 20:33:08,913 domogik-scenario DEBUG Create test instance sensor.SensorTest.68 with uuid 2f0a59c5-f672-4d99-b60a-c2f05cc4c67b
    Traceback (most recent call last):
      File "/opt/dmg/domogik-0.4.1/src/domogik/bin/scenario.py", line 128, in <module>
        ScenarioFrontend()
      File "/opt/dmg/domogik-0.4.1/src/domogik/bin/scenario.py", line 67, in __init__
        self._backend = ScenarioManager(self.log)
      File "/opt/dmg/domogik-dev/src/domogik/scenario/manager.py", line 111, in __init__
        self.load_scenarios()
      File "/opt/dmg/domogik-dev/src/domogik/scenario/manager.py", line 119, in load_scenarios
        self.create_scenario(scenario.name, scenario.json, int(scenario.id), scenario.disabled, scenario.description)
      File "/opt/dmg/domogik-dev/src/domogik/scenario/manager.py", line 192, in create_scenario
        scen = ScenarioInstance(self.log, cid, name, payload, dis)
      File "/opt/dmg/domogik-dev/src/domogik/scenario/scenario.py", line 96, in __init__
        self._instanciate()
      File "/opt/dmg/domogik-dev/src/domogik/scenario/scenario.py", line 134, in _instanciate
        self._parsed_condition = self.__parse_if_part(self._json['IF'], datatypes)
      File "/opt/dmg/domogik-dev/src/domogik/scenario/scenario.py", line 186, in __parse_if_part
        return "( {0} {1} {2} )".format(self.__parse_if_part(part['A'], datatypes), compare, self.__parse_if_part(part['B'], datatypes))
    KeyError: 'B'
    2015-10-15 20:33:23,861 domogik-scenario DEBUG Send client status : starting
    2015-10-15 20:33:38,861 domogik-scenario DEBUG Send client status : starting
    2015-10-15 20:33:53,861 domogik-scenario DEBUG Send client status : starting
    2015-10-15 20:34:08,862 domogik-scenario DEBUG Send client status : starting
    2015-10-15 20:34:23,862 domogik-scenario DEBUG Send client status : starting
    2015-10-15 20:34:38,863 domogik-scenario DEBUG Send client status : starting
    2015-10-15 20:34:53,863 domogik-scenario DEBUG Send client status : starting
    2015-10-15 20:35:08,864 domogik-scenario DEBUG Send client status : starting

**Comment by fritz-smh** [comment]
I see, it seems that you saved a non finished scenario (something compared to nothing).

I will handle this.

**Comment by vdomos** [comment]
Yes, I forget it, 
I have not succeeded to enter the 2nd test fields, impossible to write in the test widget.
I save the scenario in this state to be able to change it back.

**Comment by fritz-smh** [comment]
cereal is currenly doing some fixes that should resolve the edit issue
