### ISSUE TITLE
new install domogik 0.4.2 webif clients all dead (rpi B install)

### ISSUE THREAD

**Issue by maxs99** [domogik/domogik#148]
Hi

the the webif shows all clients are dead
but the logs of admin, manager and so on shows
2015-10-20 05:46:28,063 domogik-manager DEBUG Send client status : alive
the conf looks like the sample

**Comment by maxs99** [comment]
Hey guys nobody any idea??

**Comment by fritz-smh** [comment]
Hi,

First, are you sure you are using a 0.4.2 ?
The 0.4.1 had this bug, but it should be resolved in 0.4.2 (which by the way has been released only 3 or 4 hours ago... and there is still no official comm about it, but I must admit that some part of the doc already mentionned 0.4.2)

Can you also give me the result of :  
```
grep BIND /var/log/domogik/*
```

Thanks

**Comment by tikismoke** [comment]
I'm on master branch.
Grep bind log tomorrow if I had time.
Other way this we I should have more time.

**Comment by tikismoke** [comment]
Oups not my issue but ir looks à little.

**Comment by fritz-smh** [comment]
tikismoke : are you sure you are on the good ticket ? ;)

**Comment by maxs99** [comment]
Damm now i now why the links on the install are not working, i did download manual the zip copy over ssh to the raspi and then the rest..

**Comment by maxs99** [comment]
Sorry the same problem but now the links are working.
a request on port 40405 give this

{"info": {"REST_API_version": "0.7", "SSL": false, "Host": "raspberrypi", "Domogik_release": "0.4.2", "Domogik_version": "0.4.2", "REST_API_release": "0.7", "Sources_release": "0.4.2", "Sources_version": "0.4.2"}, "mq": {"sub_port": "40412", "ip": "192.168.50.59", "req_rep_port": "40410", "pub_port": "40411"}}

on the admin interface the clients are all dead

 Core components 6
xplgw dead
butler dead
rest dead
scenario dead
admin dead
dbmgr dead

the log
/var/log/domogik/admin.log:2015-10-21 09:36:58,637 domogik-admin INFO  - 192.168.50.59:40406 [BIND]
/var/log/domogik/manager.log:2015-10-21 09:35:45,222 domogik-manager INFO Binding to ('192.168.50.59', 0) [BIND]...
Übereinstimmungen in Binärdatei /var/log/domogik/mq_broker.log.
/var/log/domogik/mq_forwarder.log:2015-10-21 09:35:32,017 domogik-mq_forwarder INFO Waiting for messages on tcp://192.168.50.59:40411 [BIND]
/var/log/domogik/mq_forwarder.log:2015-10-21 09:35:32,054 domogik-mq_forwarder INFO Sending messages to tcp://192.168.50.59:40412 [BIND]
/var/log/domogik/rest.log:2015-10-21 09:36:19,738 domogik-rest INFO  - 192.168.50.59:40405 [BIND]
/var/log/domogik/xplgw.log:2015-10-21 09:36:30,654 domogik-xplgw INFO Binding to ('192.168.50.59', 0) [BIND]...


in the domogik-mq is the ip adress from my raspi
but you says in the install the networkcard should be used??

max

**Comment by fritz-smh** [comment]
can you do :  
```
netstat -lapute | grep 404
```
and :
```
cd /opt/dmg/domogik/src/domogik/examples/mq-python/
python req_client_list.py
```
and this one (wait for a minute and break it with ctrl-c) : 
```
cd /opt/dmg/domogik/src/domogik/examples/mq-python/
python sub_plugin_status.py 
```

**Comment by maxs99** [comment]
ok
netstat
tcp        0      0 *:40404                 *:*                     LISTEN      domoweb    149802      23666/python    
tcp        0      0 raspberrypi.m-u-m:40405 *:*                     LISTEN      domogik    158509      25746/python    
tcp        0      0 raspberrypi.m-u-m:40406 *:*                     LISTEN      domogik    158955      25821/python    
tcp        0      0 raspberrypi.m-u-m:40410 *:*                     LISTEN      domogik    157805      25588/python    
tcp        0      0 raspberrypi.m-u-m:40411 *:*                     LISTEN      domogik    157877      25600/python    
tcp        0      0 raspberrypi.m-u-m:40412 *:*                     LISTEN      domogik    157882      25600/python    
tcp        0      0 raspberrypi.m-u-m:37089 raspberrypi.m-u-m:40411 VERBUNDEN   domogik    159215      25889/python    
tcp        0      0 raspberrypi.m-u-m:40410 raspberrypi.m-u-m:38261 VERBUNDEN   domogik    159223      25588/python    
tcp        0      0 raspberrypi.m-u-m:38189 raspberrypi.m-u-m:40410 VERBUNDEN   domoweb    157807      23666/python    
tcp        0      0 raspberrypi.m-u-m:53770 raspberrypi.m-u-m:40412 VERBUNDEN   domogik    158697      25780/python    
tcp        0      0 raspberrypi.m-u-m:40410 raspberrypi.m-u-m:38258 VERBUNDEN   domogik    159109      25588/python    
tcp        0      0 raspberrypi.m-u-m:40411 raspberrypi.m-u-m:37074 VERBUNDEN   domogik    158679      25600/python    
tcp        0      0 raspberrypi.m-u-m:40411 raspberrypi.m-u-m:37089 VERBUNDEN   domogik    159216      25600/python    
tcp        0      0 raspberrypi.m-u-m:37091 raspberrypi.m-u-m:40411 VERBUNDEN   domogik    159229      25889/python    
tcp        0      0 raspberrypi.m-u-m:40412 raspberrypi.m-u-m:53786 VERBUNDEN   domogik    159236      25600/python    
tcp        0      0 raspberrypi.m-u-m:38253 raspberrypi.m-u-m:40410 VERBUNDEN   domogik    158902      25821/python    
tcp        0      0 raspberrypi.m-u-m:37064 raspberrypi.m-u-m:40411 VERBUNDEN   domogik    158074      25652/python    
tcp        0      0 raspberrypi.m-u-m:40412 raspberrypi.m-u-m:53755 VERBUNDEN   domogik    157886      25600/python    
tcp        0      0 raspberrypi.m-u-m:40412 raspberrypi.m-u-m:53760 VERBUNDEN   domogik    158243      25600/python    
tcp        0      0 raspberrypi.m-u-m:40410 raspberrypi.m-u-m:38253 VERBUNDEN   domogik    158903      25588/python    
tcp        0      0 raspberrypi.m-u-m:38239 raspberrypi.m-u-m:40410 VERBUNDEN   domogik    158330      25706/python    
tcp        0      0 raspberrypi.m-u-m:37074 raspberrypi.m-u-m:40411 VERBUNDEN   domogik    158678      25780/python    
tcp        0      0 raspberrypi.m-u-m:38261 raspberrypi.m-u-m:40410 VERBUNDEN   domogik    159222      25889/python    
tcp        0      0 raspberrypi.m-u-m:40410 raspberrypi.m-u-m:38239 VERBUNDEN   domogik    158331      25588/python    
tcp        0      0 raspberrypi.m-u-m:53759 raspberrypi.m-u-m:40412 VERBUNDEN   domogik    158080      25652/python    
tcp        0      0 raspberrypi.m-u-m:40410 raspberrypi.m-u-m:38246 VERBUNDEN   domogik    158686      25588/python    
tcp        0      0 raspberrypi.m-u-m:40410 raspberrypi.m-u-m:38243 VERBUNDEN   domogik    158504      25588/python    
tcp        0      0 raspberrypi.m-u-m:38234 raspberrypi.m-u-m:40410 VERBUNDEN   domogik    158056      25652/python    
tcp        0      0 raspberrypi.m-u-m:38257 raspberrypi.m-u-m:40410 VERBUNDEN   domogik    159093      25859/python    
tcp        0      0 raspberrypi.m-u-m:40411 raspberrypi.m-u-m:37071 VERBUNDEN   domogik    158497      25600/python    
tcp        0      0 raspberrypi.m-u-m:53764 raspberrypi.m-u-m:40412 VERBUNDEN   domogik    158426      25652/python    
tcp        0      0 raspberrypi.m-u-m:37081 raspberrypi.m-u-m:40411 VERBUNDEN   domogik    158895      25821/python    
tcp        0      0 raspberrypi.m-u-m:53760 raspberrypi.m-u-m:40412 VERBUNDEN   domogik    158242      25652/python    
tcp        0      0 raspberrypi.m-u-m:38258 raspberrypi.m-u-m:40410 VERBUNDEN   domogik    159108      25859/python    
tcp        0      0 raspberrypi.m-u-m:40411 raspberrypi.m-u-m:37091 VERBUNDEN   domogik    159230      25600/python    
tcp        0      0 raspberrypi.m-u-m:40410 raspberrypi.m-u-m:38254 VERBUNDEN   domogik    158910      25588/python    
tcp        0      0 raspberrypi.m-u-m:40411 raspberrypi.m-u-m:37085 VERBUNDEN   domogik    159087      25600/python    
tcp        0      0 raspberrypi.m-u-m:40412 raspberrypi.m-u-m:53770 VERBUNDEN   domogik    158698      25600/python    
tcp        0      0 raspberrypi.m-u-m:40410 raspberrypi.m-u-m:38234 VERBUNDEN   domogik    158057      25588/python    
tcp        0      0 raspberrypi.m-u-m:40411 raspberrypi.m-u-m:37067 VERBUNDEN   domogik    158324      25600/python    
tcp        0      0 raspberrypi.m-u-m:38254 raspberrypi.m-u-m:40410 VERBUNDEN   domogik    158909      25821/python    
tcp        0      0 raspberrypi.m-u-m:40412 raspberrypi.m-u-m:53778 VERBUNDEN   domogik    159006      25600/python    
tcp        0      0 raspberrypi.m-u-m:40412 raspberrypi.m-u-m:53767 VERBUNDEN   domogik    158598      25600/python    
tcp        0      0 raspberrypi.m-u-m:40411 raspberrypi.m-u-m:37064 VERBUNDEN   domogik    158075      25600/python    
tcp        0      0 raspberrypi.m-u-m:40411 raspberrypi.m-u-m:37062 VERBUNDEN   domogik    158050      25600/python    
tcp        0      0 raspberrypi.m-u-m:40410 raspberrypi.m-u-m:38189 VERBUNDEN   domogik    157809      25588/python    
tcp        0      0 raspberrypi.m-u-m:53755 raspberrypi.m-u-m:40412 VERBUNDEN   domoweb    157885      23666/python    
tcp        0      0 raspberrypi.m-u-m:40412 raspberrypi.m-u-m:53774 VERBUNDEN   domogik    158815      25600/python    
tcp        0      0 raspberrypi.m-u-m:53774 raspberrypi.m-u-m:40412 VERBUNDEN   domogik    158814      25652/python    
tcp        0      0 raspberrypi.m-u-m:53778 raspberrypi.m-u-m:40412 VERBUNDEN   domogik    159005      25652/python    
tcp        0      0 raspberrypi.m-u-m:40412 raspberrypi.m-u-m:53759 VERBUNDEN   domogik    158081      25600/python    
tcp        0      0 raspberrypi.m-u-m:40411 raspberrypi.m-u-m:37077 VERBUNDEN   domogik    158712      25600/python    
tcp        0      0 raspberrypi.m-u-m:37085 raspberrypi.m-u-m:40411 VERBUNDEN   domogik    159086      25859/python    
tcp        0      0 raspberrypi.m-u-m:40411 raspberrypi.m-u-m:37081 VERBUNDEN   domogik    158896      25600/python    
tcp        0      0 raspberrypi.m-u-m:37077 raspberrypi.m-u-m:40411 VERBUNDEN   domogik    158711      25780/python    
tcp        0      0 raspberrypi.m-u-m:40410 raspberrypi.m-u-m:38257 VERBUNDEN   domogik    159094      25588/python    
tcp        0      0 raspberrypi.m-u-m:37062 raspberrypi.m-u-m:40411 VERBUNDEN   domogik    158049      25652/python    
tcp        0      0 raspberrypi.m-u-m:53786 raspberrypi.m-u-m:40412 VERBUNDEN   domogik    159235      25889/python    
tcp        0      0 raspberrypi.m-u-m:53767 raspberrypi.m-u-m:40412 VERBUNDEN   domogik    158597      25652/python    
tcp        0      0 raspberrypi.m-u-m:37067 raspberrypi.m-u-m:40411 VERBUNDEN   domogik    158323      25706/python    
tcp        0      0 raspberrypi.m-u-m:38246 raspberrypi.m-u-m:40410 VERBUNDEN   domogik    158685      25780/python    
tcp        0      0 raspberrypi.m-u-m:40412 raspberrypi.m-u-m:53764 VERBUNDEN   domogik    158427      25600/python    
tcp        0      0 raspberrypi.m-u-m:38243 raspberrypi.m-u-m:40410 VERBUNDEN   domogik    158503      25746/python    
tcp        0      0 raspberrypi.m-u-m:37071 raspberrypi.m-u-m:40411 VERBUNDEN   domogik    158496      25746/python

**Comment by maxs99** [comment]
client list

['client.list.result', '{"core-xplgw.raspberrypi": {"status": "dead", "name": "xplgw", "xpl_source": "domogik-xplgw.raspberrypi", "xpl_clients_only": [], "pid": 25744, "package_id": "core-xplgw", "host": "raspberrypi", "compliant_xpl_clients": [], "type": "core", "configured": null, "last_seen": 1445412989.126623}, "core-butler.raspberrypi": {"status": "dead", "name": "butler", "xpl_source": "domogik-butler.raspberrypi", "xpl_clients_only": [], "pid": 25865, "package_id": "core-butler", "host": "raspberrypi", "compliant_xpl_clients": [], "type": "core", "configured": null, "last_seen": 1445413029.551781}, "core-rest.raspberrypi": {"status": "dead", "name": "rest", "xpl_source": "domogik-rest.raspberrypi", "xpl_clients_only": [], "pid": 25711, "package_id": "core-rest", "host": "raspberrypi", "compliant_xpl_clients": [], "type": "core", "configured": null, "last_seen": 1445412977.671805}, "core-scenario.raspberrypi": {"status": "dead", "name": "scenario", "xpl_source": "domogik-scenario.raspberrypi", "xpl_clients_only": [], "pid": 25825, "package_id": "core-scenario", "host": "raspberrypi", "compliant_xpl_clients": [], "type": "core", "configured": null, "last_seen": 1445413019.027214}, "core-admin.raspberrypi": {"status": "dead", "name": "admin", "xpl_source": "domogik-admin.raspberrypi", "xpl_clients_only": [], "pid": 25788, "package_id": "core-admin", "host": "raspberrypi", "compliant_xpl_clients": [], "type": "core", "configured": null, "last_seen": 1445413006.630416}, "core-dbmgr.raspberrypi": {"status": "dead", "name": "dbmgr", "xpl_source": "domogik-dbmgr.raspberrypi", "xpl_clients_only": [], "pid": 25674, "package_id": "core-dbmgr", "host": "raspberrypi", "compliant_xpl_clients": [], "type": "core", "configured": null, "last_seen": 1445412959.750817}}']

**Comment by maxs99** [comment]
plugin status

^CTraceback (most recent call last):
  File "sub_plugin_status.py", line 51, in <module>
    Test()
  File "sub_plugin_status.py", line 44, in __init__
    IOLoop.instance().start()
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-armv6l.egg/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.2.1-py2.7-linux-armv6l.egg/tornado/ioloop.py", line 841, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-armv6l.egg/zmq/eventloop/ioloop.py", line 122, in poll
    z_events = self._poller.poll(1000*timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-armv6l.egg/zmq/sugar/poll.py", line 101, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 115, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:1625)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:1958)
KeyboardInterrupt

**Comment by fritz-smh** [comment]
Did you wait for about a minute for the last one ?

Can you show us the /var/log/domogik/mq* log files ?

Thanks

**Comment by maxs99** [comment]
öhm not check by watch i will do it again

mq log

root@raspberrypi:~# tail -f /var/log/domogik/mq*.log
==> /var/log/domogik/mq_broker.log <==
2015-10-21 09:37:00,631 domogik-mq_broker DEBUG Client REQ received: to='mmi.services' data=['']
2015-10-21 09:37:00,639 domogik-mq_broker DEBUG WORKER REP received: from='mmi.services' data=['rest, xplgw, admin, dbmgr']
2015-10-21 09:37:04,418 domogik-mq_broker DEBUG Try to register a worker : wid=����kH��B���, service=scenario
2015-10-21 09:37:04,426 domogik-mq_broker INFO Registered worker : wid=����kH��B���, service=scenario
2015-10-21 09:37:09,716 domogik-mq_broker DEBUG Try to register a worker : wid=N=}V��DK�����e��, service=manager
2015-10-21 09:37:09,719 domogik-mq_broker INFO Registered worker : wid=N=}V��DK�����e��, service=manager
2015-10-21 09:37:11,486 domogik-mq_broker DEBUG Try to register a worker : wid=�a��hM:�F�F'���, service=butler
2015-10-21 09:37:11,495 domogik-mq_broker INFO Registered worker : wid=�a��hM:�F�F'���, service=butler
2015-10-21 10:56:19,937 domogik-mq_broker DEBUG Client REQ received: to='manager' data=['client.list.get', '{}']
2015-10-21 10:56:19,984 domogik-mq_broker DEBUG WORKER REP received: from='manager' data=['client.list.result', '{"core-xplgw.raspberrypi": {"status": "dead", "xpl_clients_only": [], "pid": 25744, "host": "raspberrypi", "name": "xplgw", "xpl_source": "domogik-xplgw.raspberrypi", "package_id": "core-xplgw", "compliant_xpl_clients": [], "type": "core", "configured": null, "last_seen": 1445412989.126623}, "core-butler.raspberrypi": {"status": "dead", "xpl_clients_only": [], "pid": 25865, "host": "raspberrypi", "name": "butler", "xpl_source": "domogik-butler.raspberrypi", "package_id": "core-butler", "compliant_xpl_clients": [], "type": "core", "configured": null, "last_seen": 1445413029.551781}, "core-rest.raspberrypi": {"status": "dead", "xpl_clients_only": [], "pid": 25711, "host": "raspberrypi", "name": "rest", "xpl_source": "domogik-rest.raspberrypi", "package_id": "core-rest", "compliant_xpl_clients": [], "type": "core", "configured": null, "last_seen": 1445412977.671805}, "core-scenario.raspberrypi": {"status": "dead", "xpl_clients_only": [], "pid": 25825, "host": "raspberrypi", "name": "scenario", "xpl_source": "domogik-scenario.raspberrypi", "package_id": "core-scenario", "compliant_xpl_clients": [], "type": "core", "configured": null, "last_seen": 1445413019.027214}, "core-admin.raspberrypi": {"status": "dead", "xpl_clients_only": [], "pid": 25788, "host": "raspberrypi", "name": "admin", "xpl_source": "domogik-admin.raspberrypi", "package_id": "core-admin", "compliant_xpl_clients": [], "type": "core", "configured": null, "last_seen": 1445413006.630416}, "core-dbmgr.raspberrypi": {"status": "dead", "xpl_clients_only": [], "pid": 25674, "host": "raspberrypi", "name": "dbmgr", "xpl_source": "domogik-dbmgr.raspberrypi", "package_id": "core-dbmgr", "compliant_xpl_clients": [], "type": "core", "configured": null, "last_seen": 1445412959.750817}}']

==> /var/log/domogik/mq_forwarder.log <==
2015-10-21 09:35:31,976 domogik-mq_forwarder INFO Starting the forwarder
2015-10-21 09:35:32,017 domogik-mq_forwarder INFO Waiting for messages on tcp://192.168.50.59:40411 [BIND]
2015-10-21 09:35:32,054 domogik-mq_forwarder INFO Sending messages to tcp://192.168.50.59:40412 [BIND]
2015-10-21 09:35:32,063 domogik-mq_forwarder INFO Forwarding messages...

**Comment by maxs99** [comment]
plugin_status.py  71sec

oot@raspberrypi:/opt/dmg/domogik/src/domogik/examples/mq-python# python sub_plugin_status.py 

^CTraceback (most recent call last):
  File "sub_plugin_status.py", line 51, in <module>
    Test()
  File "sub_plugin_status.py", line 44, in __init__
    IOLoop.instance().start()
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-armv6l.egg/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.2.1-py2.7-linux-armv6l.egg/tornado/ioloop.py", line 841, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-armv6l.egg/zmq/eventloop/ioloop.py", line 122, in poll
    z_events = self._poller.poll(1000*timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-armv6l.egg/zmq/sugar/poll.py", line 101, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 115, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:1625)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:1958)
KeyboardInterrupt
root@raspberrypi:/opt/dmg/domogik/src/domogik/examples/mq-python#

**Comment by fritz-smh** [comment]
can you try :  

python sub_all.py 

and also wait for about 1 minute

**Comment by fritz-smh** [comment]
by the way, what is your platform ? cpu, ram ?

**Comment by maxs99** [comment]
raspi b not plus         sd class 8 oder 10        size 6 or 8 gd

root@raspberrypi:/opt/dmg/domogik/src/domogik/examples/mq-python# python sub_all.py 
^CTraceback (most recent call last):
  File "sub_all.py", line 20, in <module>
    Test()
  File "sub_all.py", line 13, in __init__
    IOLoop.instance().start()
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-armv6l.egg/zmq/eventloop/ioloop.py", line 151, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.2.1-py2.7-linux-armv6l.egg/tornado/ioloop.py", line 841, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-armv6l.egg/zmq/eventloop/ioloop.py", line 122, in poll
    z_events = self._poller.poll(1000*timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-14.7.0-py2.7-linux-armv6l.egg/zmq/sugar/poll.py", line 101, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 115, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:1625)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:1958)
KeyboardInterrupt
root@raspberrypi:/opt/dmg/domogik/src/domogik/examples/mq-python#

**Comment by maxs99** [comment]
incidentally 
the velbus plugin how diffitcult is it to ad a gateway function for programming the bus??

**Comment by Cereal2nd** [comment]
not possible, but i'm using a velbus tcp gateway and connect to that one
with velbuslink and with the domogik plugin at the same time

**Comment by fritz-smh** [comment]
@maxs99 : domogik is using too much memory for rpi b/b+
I tried in my side and it is not usable. We will do improvments for later releases on memory footprint. But for now, forget using domogik on a rpi (except rpi2 which should be ok)

**Comment by maxs99** [comment]
okoidoki 
what do you all mean should i use for my homeautomation with velbus
velbus is a cool system but for a complex control the end cames really fast
raspis did i have so why not i have tried domotiga ...........
domogik i have for a long time with the raspi but i was realy slow so projekt stop
after a year a looked around 
and now i am again here 

thx for looking in my trouble

**Comment by fritz-smh** [comment]
Sorry, I have difficulties to understand your last comment. Can you reformulate it ?

**Comment by fritz-smh** [comment]
Hi, still waiting ;)

**Comment by jschaeke** [comment]
Hi cereal, which velbus tcp gateway are you using? Would like to use it too... is it part of the velbuslink software? Or is it one of the c-files that float around in the Velleman forum..

**Comment by Cereal2nd** [comment]
Its the one from jeroend on the velleman forum

**Comment by fritz-smh** [comment]
If no news, I will close this ticket ;)
