### ISSUE TITLE
merge admin/rest : Error while accessing /rest/device/ url on the merged component

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#167]
Here is the error

```
2015-11-09 16:08:58,277 domogik-admin DEBUG Send client status : alive                                                  
2015-11-09 16:09:03,440 domogik.admin.application ERROR Exception on /rest/device/ [GET]                                
Traceback (most recent call last):                                                                                      
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app             
    response = self.full_dispatch_request()                                                                             
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)                                                                                  
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)                                                                                    
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()                                                                                        
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request     
    return self.view_functions[rule.endpoint](**req.view_args)                                                          
  File "/media/stock/domotique/git/domogik/src/domogik/admin/application.py", line 103, in timed                        
    result = action_func(*args, **kw)                                                                                   
  File "/media/stock/domotique/git/domogik/src/domogik/admin/application.py", line 114, in create_json_response         
    ret = action_func(*args, **kwargs)                                                                                  
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/views.py", line 84, in view                 
    return self.dispatch_request(*args, **kwargs)                                                                       
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/views.py", line 149, in dispatch_request    
    return meth(*args, **kwargs)                                                                                        
  File "/media/stock/domotique/git/domogik/src/domogik/admin/rest/device.py", line 171, in get                          
    b = app.db.list_devices()                                                                                           
  File "/media/stock/domotique/git/domogik/src/domogik/common/database.py", line 384, in list_devices                   
    for device in self.__session.query(Device).all():                                                                   
AttributeError: 'NoneType' object has no attribute 'query'                
```

**Comment by Cereal2nd** [comment]
should be solved in latest version
