### ISSUE TITLE
Error Starting 0MQ broker on fresh install RPI 2

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#183]
Hello, 
After installing domogik on RPI 2, I have this error when starting domogik:

    # /etc/init.d/domogik start
     * Starting 0MQ broker ...Traceback (most recent call last):
      File "/usr/local/bin/dmg_broker", line 9, in <module>
        load_entry_point('Domogik-MQ==1.1', 'console_scripts', 'dmg_broker')()
      File "/opt/dmg/domogik-mq/src/domogikmq/reqrep/broker.py", line 606, in main
        stdout=sys.stdout):
      File "/usr/local/lib/python2.7/dist-packages/python_daemon-2.1.0-py2.7.egg/daemon/daemon.py", line 394, in __enter__
        self.open()
      File "/usr/local/lib/python2.7/dist-packages/python_daemon-2.1.0-py2.7.egg/daemon/daemon.py", line 370, in open
        change_process_owner(self.uid, self.gid, self.initgroups)
      File "/usr/local/lib/python2.7/dist-packages/python_daemon-2.1.0-py2.7.egg/daemon/daemon.py", line 642, in change_process_owner
        raise error
    daemon.daemon.DaemonOSEnvironmentError: Unable to change process owner ([Errno 1] Operation not permitted)
     An error occured during 0MQ broker startup.

domogik and domogig-mq installed by git:

    git clone https://github.com/domogik/domogik-mq.git
    git clone https://github.com/domogik/domogik.git

Same error with domogik user:

    # grep USER /etc/default/domogik                   
    DOMOGIK_USER=dan

    dan@vesta:~$ dmg_broker -f
    Traceback (most recent call last):
      File "/usr/local/bin/dmg_broker", line 9, in <module>
        load_entry_point('Domogik-MQ==1.1', 'console_scripts', 'dmg_broker')()
      File "/opt/dmg/domogik-mq/src/domogikmq/reqrep/broker.py", line 606, in main
        stdout=sys.stdout):
      File "/usr/local/lib/python2.7/dist-packages/python_daemon-2.1.0-py2.7.egg/daemon/daemon.py", line 394, in __enter__
        self.open()
      File "/usr/local/lib/python2.7/dist-packages/python_daemon-2.1.0-py2.7.egg/daemon/daemon.py", line 370, in open
        change_process_owner(self.uid, self.gid, self.initgroups)
      File "/usr/local/lib/python2.7/dist-packages/python_daemon-2.1.0-py2.7.egg/daemon/daemon.py", line 642, in change_process_owner
        raise error
    daemon.daemon.DaemonOSEnvironmentError: Unable to change process owner ([Errno 1] Operation not permitted)

0mq version:

    $ pip list|grep -i zmq
    pyzmq (14.4.0)
    $ dpkg -l|grep -i python-zmq
    ii  python-zmq                            14.4.0-1                                  armhf        Python bindings for 0MQ library

Any idea of this probleme ?

thanks,

**Comment by fritz-smh** [comment]
No idea but you are not the only one to got this the last days...
Which domogik release are you installing ?

**Comment by fritz-smh** [comment]
Maybe a relationship with a new python-daemon package ?

On my side I got this one : python-daemon==1.6.1

**Comment by vdomos** [comment]
Same version on my Domogik VM and rpi2
python-daemon                         1.5.5-1 

No error with domogik vm

**Comment by fritz-smh** [comment]
I reproduced the issue with python-daemon 2.1.0.

**Comment by fritz-smh** [comment]
Can you test again with this new Domogik-MQ release : https://github.com/domogik/domogik-mq/archive/1.3.zip

And tell me if this is ok ;)

**Comment by vdomos** [comment]
Ok, I will test this evening.

I just replace the domogik-mq directory download from git by your zip version ?

**Comment by fritz-smh** [comment]
yes, and redo the install of domogik-mq also ;)

**Comment by fritz-smh** [comment]
especially the config part

**Comment by vdomos** [comment]
Good, started on rpi2:

    # /etc/init.d/domogik start
     * Starting 0MQ broker ... Done.
     * Starting 0MQ forwarder ... Done.
     * Starting xPL (python version) ... Done.
     * Starting Manager (with -a -d -r -x -s -b) ...  Done.

Test with diskfree plugin : ok

**Comment by fritz-smh** [comment]
Published on the website and on the 0.4.2 installation doc.
