### ISSUE TITLE
xplgw fall if plugin name has more than 8 characters

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#186]
Yes, I know that plugin must have 8 characters maximum, 
but if this precaution is forgotten xplgw falls and no longer responds to queries.

The first REST query dropped XPLGW and after it stops responding to other:

rest.log

    2015-12-01 00:16:24,316 domogik.rest.url INFO http request GET for /cmd/id/42 received
    2015-12-01 00:16:26,714 domogik-rest DEBUG Send client status : alive
    2015-12-01 00:16:34,325 domogik.rest.url DEBUG performance|api_ncommand|()|{'cid': 42}|10.0084888935
    2015-12-01 00:16:34,325 domogik.rest.url DEBUG  => response status code: 400
    2015-12-01 00:16:34,325 domogik.rest.url DEBUG  => response content_type: application/json
    2015-12-01 00:16:34,325 domogik.rest.url DEBUG  => response data: ['{"msg": "XPL gateway does not respond"}']
    2015-12-01 00:16:41,714 domogik-rest DEBUG Send client status : alive
    2015-12-01 00:16:56,714 domogik-rest DEBUG Send client status : alive
      
    2015-12-01 00:17:00,956 domogik.rest.url INFO http request GET for /cmd/id/7 received
    2015-12-01 00:17:10,966 domogik.rest.url DEBUG performance|api_ncommand|()|{'cid': 7}|10.0099039078
    2015-12-01 00:17:10,966 domogik.rest.url DEBUG  => response status code: 400
    2015-12-01 00:17:10,966 domogik.rest.url DEBUG  => response content_type: application/json
    2015-12-01 00:17:10,966 domogik.rest.url DEBUG  => response data: ['{"msg": "XPL gateway does not respond"}']

 xplgw.log

    2015-12-01 00:16:24,318 domogik-xplgw DEBUG MQ Request received : <MQMessage(action=cmd.send, data='{u'cmdid': 42, u'cmdparams': {u'body': u'bonjour'}}')>
    2015-12-01 00:16:24,318 domogik-xplgw INFO Received new cmd request: <MQMessage(action=cmd.send, data='{u'cmdid': 42, u'cmdparams': {u'body': u'bonjour'}}')>
    2015-12-01 00:16:24,377 domogik-xplgw ERROR Traceback (most recent call last):
      File "/opt/dmg/domogik-dev/src/domogik/bin/xplgw.py", line 114, in on_mdp_request
        self._send_xpl_command(msg)
      File "/opt/dmg/domogik-dev/src/domogik/bin/xplgw.py", line 205, in _send_xpl_command
       msg.set_target(self.client_xpl_map[dev['client_id']])
      File "/opt/dmg/domogik-dev/src/domogik/xpl/common/xplmessage.py", line 305, in set_target
        raise XplMessageError("Invalid target (%s)" % target)
    XplMessageError: Invalid target (domogik-pushbullet.ares)

After changing the name of the plugin, no problem

Need a test in the plugin's discovery  ?

**Comment by Cereal2nd** [comment]
its alread solved in develop

**Comment by fritz-smh** [comment]
So closing ;)
