### ISSUE TITLE
Xpl zmq error on start

### ISSUE THREAD

**Issue by deennoo** [domogik/domogik#194]
Hi,

Got a probleme after installing Domogik and run domogik start : 

android@localhost:/opt/dmg/domogik$ sudo /etc/init.d/domogik start
 * Starting 0MQ broker ...No directory, logging in with HOME=/
 Done.
 * Starting 0MQ forwarder ... Done.
 * Starting xPL (python version) ...No directory, logging in with HOME=/
Traceback (most recent call last):
  File "/usr/local/bin/dmg_broker", line 9, in <module>
    load_entry_point('Domogik-MQ==1.3', 'console_scripts', 'dmg_broker')()
  File "/opt/dmg/domogik-mq-1.3/src/domogikmq/reqrep/broker.py", line 616, in main
    broker = MDPBroker(context, "tcp://{0}:{1}".format(config['ip'], config['req_rep_port']))
  File "/opt/dmg/domogik-mq-1.3/src/domogikmq/reqrep/broker.py", line 88, in __init__
    socket.bind(main_ep)
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
zmq.error.ZMQError: Permission denied
 Done.
 * Starting Manager (with -a -d -r -x -s -b) ...  Done.

i saw permission denied but how to solve it ?

**Comment by Cereal2nd** [comment]
After some investigation it seems this was an android device

**Comment by deennoo** [comment]
yeap, issue solve
