### ISSUE TITLE
Cannot assign requested address

### ISSUE THREAD

**Issue by zadmalck** [domogik/domogik#208]
If ip address (dhcp with MAC by router) is changed : 

 /etc/init.d/domogik start

 * Starting 0MQ broker ... Done.
 * Starting 0MQ forwarder ... Done.
 * Starting xPL (python version) ... Done.
 * Starting Manager (with -a -d -x -s -b) ... Traceback (most recent call last):
  File "/usr/local/bin/dmg_broker", line 9, in <module>
    load_entry_point('Domogik-MQ==1.3', 'console_scripts', 'dmg_broker')()
  File "/opt/dmg/domogik-mq/src/domogikmq/reqrep/broker.py", line 616, in main
    broker = MDPBroker(context, "tcp://{0}:{1}".format(config['ip'], config['req_rep_port']))
  File "/opt/dmg/domogik-mq/src/domogikmq/reqrep/broker.py", line 88, in __init__
    socket.bind(main_ep)
  File "socket.pyx", line 444, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:4124)
  File "checkrc.pxd", line 21, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:6103)
zmq.error.ZMQError: Cannot assign requested address
 Done.

**Comment by fritz-smh** [comment]
Domogik server must have a static ip. Please configure your dhcp server in order to do this :)
