### ISSUE TITLE
Scenario: Error with setting variable with a direct value

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#227]
Hello, I have this error with this scenario:

The old value are replaced by 'null' instead of the given value.

![domogik_scenario_variable_4](https://cloud.githubusercontent.com/assets/1257481/12599195/38d23c68-c490-11e5-9904-d6511c2df320.png)

    2016-01-27 00:00:31,561 domogik-scenario DEBUG Evaluate <domogik.scenario.parameters.cron.CronParameter instance at 0x7f36d404a440> : True
    2016-01-27 00:00:31,561 domogik-scenario DEBUG Evaluate <domogik.scenario.parameters.cron.CronParameter instance at 0x7f36d404a440> : True
    2016-01-27 00:00:31,562 domogik-scenario DEBUG _parsed condition is : self._mapping['test']['004c008f-032a-40c0-b937-b0b209771966'].evaluate(), eval is True
    2016-01-27 00:00:31,562 domogik-scenario INFO Condition Raz Min Max temp Ext evaluated to True
    2016-01-27 00:00:31,563 domogik-scenario DEBUG CALLING actions. Local vars = '{'foo': 'bar'}'
    2016-01-27 00:00:31,563 domogik-scenario DEBUG Before action n°1. Local vars = '{'foo': 'bar'}'
    2016-01-27 00:00:31,563 domogik-scenario INFO Variable name=varRaz
    2016-01-27 00:00:31,564 domogik-scenario INFO Variable value={u'NUM': u'99', u'type': u'DT_Temp', u'id': u'8XM/V1noylh5BFjY;}w)'}
    2016-01-27 00:00:31,564 domogik-scenario INFO Updated local variables : '{'foo': 'bar', 'varRaz': 'null'}'
    2016-01-27 00:00:31,564 domogik-scenario DEBUG After action n°1. Local vars = '{'foo': 'bar', 'varRaz': 'null'}'
    2016-01-27 00:00:31,565 domogik-scenario DEBUG Before action n°2. Local vars = '{'foo': 'bar', 'varRaz': 'null'}'
    2016-01-27 00:00:31,565 domogik-scenario INFO Do an action...
    2016-01-27 00:00:31,565 domogik-scenario DEBUG Preprocessing on parameters...
    2016-01-27 00:00:31,566 domogik-scenario DEBUG Parameters before processing : {u'value': u'{{varRaz}}', u'NEXT': {u'NEXT': {u'value': u'{{varRaz}}'}, u'value': {u'NUM': u'-99', u'type': u'DT_Temp', u'id': u':%UTT90o,=+LEUx!`)25'}, u'name': u'varRaz'}}
    => foo
    {{varRaz}}
    => varRaz
    null
    => foo
    2016-01-27 00:00:31,582 domogik-scenario ERROR Error while replacing local variables '{'foo': 'bar', 'varRaz': 'null'}' in '{u'NEXT': {u'value': u'{{varRaz}}'}, u'value': {u'NUM': u'-99', u'type': u'DT_Temp', u'id': u':%UTT90o,=+LEUx!`)25'}, u'name': u'varRaz'}'. Error is : Traceback (most recent call last):
      File "/opt/dmg/domogik/src/domogik/scenario/actions/abstract.py", line 142, in process_local_vars
        input = input.replace(u"{{{{{0}}}}}".format(a_var), local_vars[a_var])
        AttributeError: 'dict' object has no attribute 'replace'

    2016-01-27 00:00:31,583 domogik-scenario DEBUG Parameters after processing : {u'value': u'null', u'NEXT': {u'NEXT': {u'value': u'{{varRaz}}'}, u'value': {u'NUM': u'-99', u'type': u'DT_Temp', u'id': u':%UTT90o,=+LEUx!`)25'}, u'name': u'varRaz'}}
    2016-01-27 00:00:31,583 domogik-scenario DEBUG Send action command over MQ...
    2016-01-27 00:00:31,584 domogik-scenario DEBUG Command id = '60', command params = '{u'value': u'null', u'NEXT': {u'NEXT': {u'value': u'{{varRaz}}'}, u'value': {u'NUM': u'-99', u'type': u'DT_Temp', u'id': u':%UTT90o,=+LEUx!`)25'}, u'name': u'varRaz'}}'
    2016-01-27 00:00:31,602 domogik-scenario DEBUG Action done
    2016-01-27 00:00:31,603 domogik-scenario DEBUG After action n°2. Local vars = '{'foo': 'bar', 'varRaz': 'null'}'
    2016-01-27 00:00:31,603 domogik-scenario DEBUG Before action n°3. Local vars = '{'foo': 'bar', 'varRaz': 'null'}'
    2016-01-27 00:00:31,603 domogik-scenario INFO Variable name=varRaz
    2016-01-27 00:00:31,603 domogik-scenario INFO Variable value={u'NUM': u'-99', u'type': u'DT_Temp', u'id': u':%UTT90o,=+LEUx!`)25'}
    2016-01-27 00:00:31,603 domogik-scenario INFO Updated local variables : '{'foo': 'bar', 'varRaz': 'null'}'
    2016-01-27 00:00:31,603 domogik-scenario DEBUG After action n°3. Local vars = '{'foo': 'bar', 'varRaz': 'null'}'
    2016-01-27 00:00:31,603 domogik-scenario DEBUG Before action n°4. Local vars = '{'foo': 'bar', 'varRaz': 'null'}'
    2016-01-27 00:00:31,603 domogik-scenario INFO Do an action...
    2016-01-27 00:00:31,603 domogik-scenario DEBUG Preprocessing on parameters...
    2016-01-27 00:00:31,603 domogik-scenario DEBUG Parameters before processing : {u'value': u'{{varRaz}}'}
    => foo
    {{varRaz}}
    => varRaz
    null
    2016-01-27 00:00:31,603 domogik-scenario DEBUG Parameters after processing : {u'value': u'null'}
    2016-01-27 00:00:31,603 domogik-scenario DEBUG Send action command over MQ...
    2016-01-27 00:00:31,604 domogik-scenario DEBUG Command id = '61', command params = '{u'value': u'null'}'
    2016-01-27 00:00:31,634 domogik-scenario DEBUG Action done
    2016-01-27 00:00:31,635 domogik-scenario DEBUG After action n°4. Local vars = '{'foo': 'bar', 'varRaz': 'null'}'
    2016-01-27 00:00:31,635 domogik-scenario DEBUG END CALLING actions
    Exception in thread pollthread:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/opt/dmg/domogik/src/domogik/scenario/tests/sensor.py", line 72, in _fetch
        new = self._convert(sensor.last_value)
      File "/opt/dmg/domogik/src/domogik/scenario/tests/sensor.py", line 81, in _convert
        return float(val)
    ValueError: could not convert string to float: null
    Exception in thread pollthread:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/opt/dmg/domogik/src/domogik/scenario/tests/sensor.py", line 72, in _fetch
        new = self._convert(sensor.last_value)
      File "/opt/dmg/domogik/src/domogik/scenario/tests/sensor.py", line 81, in _convert
        return float(val)
    ValueError: could not convert string to float: null

**Comment by tikismoke** [comment]
Fritz tell me this usage is not implement for now but only with sensors for the moment.

**Comment by fritz-smh** [comment]
This is not an error but a missing feature ;)
Currently only sensors input are handled.

I will add something to process other input types.

**Comment by vdomos** [comment]
Ok, no problem
thanks

**Comment by Cereal2nd** [comment]
its solved in the newscenario branch
