### ISSUE TITLE
WTForms conflict between domogik/domoweb

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#238]
Both in develop:

Domogik install WTForms 1.0.5 (/usr/local/lib/python2.7/dist-packages/WTForms-1.0.5-py2.7.egg
If install after domoweb
```
Service domogik start
 * Starting 0MQ broker ... Done.
 * Starting 0MQ forwarder ... Done.
 * Starting xPL (python version) ...Traceback (most recent call last):
  File "/usr/local/bin/dmg_broker", line 9, in <module>
    load_entry_point('Domogik-MQ==1.3', 'console_scripts', 'dmg_broker')()
  File "/home/domogik-mq/src/domogikmq/reqrep/broker.py", line 616, in main
    broker = MDPBroker(context, "tcp://{0}:{1}".format(config['ip'], config['req_rep_port']))
  File "/home/domogik-mq/src/domogikmq/reqrep/broker.py", line 88, in __init__
    socket.bind(main_ep)
  File "zmq/backend/cython/socket.pyx", line 487, in zmq.backend.cython.socket.Socket.bind (zmq/backend/cython/socket.c:5156)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
zmq.error.ZMQError: Address already in use
Traceback (most recent call last):
  File "/usr/local/bin/dmg_hub", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2711, in <module>
    parse_requirements(__requires__), Environment()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: WTForms>=1.0.5,<2.0
 An error occured during Xpl startup.
```

Domoweb install and required: 'WTForms>=2.0'

```
sudo -u domoweb /usr/bin/python /home/domoweb/Domoweb.py
sudo: unable to resolve host domogik
Traceback (most recent call last):
  File "/home/domoweb/Domoweb.py", line 13, in <module>
    from domoweb.handlers import MainHandler, ConfigurationHandler, WSHandler, NoCacheStaticFileHandler, MQHandler, UploadHandler,MultiStaticFileHandler
  File "/home/domoweb/domoweb/handlers.py", line 10, in <module>
    from domoweb.forms import WidgetInstanceForms, WidgetStyleForm
  File "/home/domoweb/domoweb/forms.py", line 3, in <module>
    pkg_resources.require("WTForms>=2.0")
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 588, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (WTForms 1.0.5 (/usr/local/lib/python2.7/dist-packages/WTForms-1.0.5-py2.7.egg), Requirement.parse('WTForms>=2.0'))
```

**Comment by Cereal2nd** [comment]
hmm

in domogik we require Flask-WTF
Flask-WTF==0.10.1
  - Flask [installed: 0.8]
    - Werkzeug [required: >=0.6.1, installed: 0.11.4]
    - Jinja2 [required: >=2.4, installed: 2.8]
      - MarkupSafe [installed: 0.23]
  - Werkzeug [required: >=0.9.5, installed: 0.11.4]
  - WTForms [required: >=1.0.5, installed: 2.0.2]

In domoweb we have:
        'WTForms >= 2.0',
        'WTForms-Components',

So should not be a problem

**Comment by tikismoke** [comment]
When installing domogik i have this:

```
Using /usr/local/lib/python2.7/dist-packages
Searching for WTForms==1.0.5
Best match: WTForms 1.0.5
Processing WTForms-1.0.5-py2.7.egg
Removing WTForms 2.1 from easy-install.pth file
WTForms 1.0.5 is already the active version in easy-install.pth
```

**Comment by Cereal2nd** [comment]
What is your version of flask-wtf?

**Comment by tikismoke** [comment]
```
Flask-WTF in /usr/local/lib/python2.7/dist-packages/Flask_WTF-0.9.5-py2.7.egg
Flask in /usr/local/lib/python2.7/dist-packages (from Flask-WTF)
```

I'm trying to upgrade to see.
