### ISSUE TITLE
time.now test error

### ISSUE THREAD

**Issue by Cereal2nd** [domogik/domogik#247]
2016-02-29 09:41:37,329 domogik-scenario DEBUG Get parameters for the test
Exception in thread pollthread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/cereal/domogik/src/domogik/scenario/tests/time_now.py", line 51, in _fetch
    self._trigger(self)
TypeError: 'NoneType' object is not callable

**Comment by fritz-smh** [comment]
Seems there is no more the error (iirc I fixed it).
Closing
