### ISSUE TITLE
﻿Scenario: Can not clone or create a new scenario

### ISSUE THREAD

**Issue by axboct** [domogik/domogik#249]
```
2016-02-29 20:18:54,113 domogik-scenario INFO Create or save scenario : name = '0', id = '0', json = '{"type":"dom_condition","id":"tK$=6w${_!65c|Ara#}/","IF":{"type":"logic_compare","id":"S!5{)no:OhJG,h#?gtc8","OP":"EQ","A":{"type":"sensor.SensorTest.65","id":"HSvj4RF]WGINHzJhcQsT"},"B":{"type":"DT_Switch","id":"_nByMbkdGdccP0Z1L7[$","BOOL":"1"}},"DO":{"type":"butler.ButlerAction","id":"M)#`pHVuA^27.AE4YUuO","media":"*","location":"","text":"Все работает"},"deletable":false}'
2016-02-29 20:18:54,114 domogik-scenario ERROR Exception occured during message processing.
2016-02-29 20:18:54,115 domogik-scenario DEBUG Traceback (most recent call last):
  File "/home/sasa/domogik/src/domogik/bin/scenario.py", line 111, in on_mdp_request
    payload = mapping[msg.get_action().split('.')[0]][msg.get_action().split('.')[1]](**msg.get_data())
  File "/home/sasa/domogik/src/domogik/scenario/manager.py", line 147, in update_scenario
    return self.create_scenario(name, json_input, cid, dis, desc, state, tmode, True)
  File "/home/sasa/domogik/src/domogik/scenario/manager.py", line 194, in create_scenario
    scen = self._db.add_scenario(name, json_input, dis, desc, tmode, False)
TypeError: add_scenario() takes exactly 6 arguments (7 given)
```

**Comment by Cereal2nd** [comment]
solved
