### ISSUE TITLE
Butler : Name in unicode

### ISSUE THREAD

**Issue by axboct** [domogik/domogik#256]
Error when trying to give the butler russian name
```
~/domogik/src/domogik/bin$ ./butler.py -f
/!\ Rivescript 1.80, patched for Domogik purpose
2016-03-03 22:30:47,740 domogik-butler INFO Looking for launched instances of 'butler'
2016-03-03 22:30:47,760 domogik-butler INFO No existing process.
2016-03-03 22:30:47,762 domogik-butler DEBUG watcher fork
2016-03-03 22:30:47,762 domogik-butler INFO ----------------------------------
2016-03-03 22:30:47,763 domogik-butler INFO Starting client 'butler' (new manager instance)
2016-03-03 22:30:47,764 domogik-butler INFO Python version is sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)
2016-03-03 22:30:47,766 domogik-butler DEBUG Send client status : starting
2016-03-03 22:30:47,767 domogik-butler DEBUG Send client status : starting
2016-03-03 22:30:47,769 domogik-butler DEBUG Write pid file for pid '17345' in file '/var/run/domogik/butler.pid'
2016-03-03 22:30:47,770 domogik-butler INFO End init of the global client part
2016-03-03 22:30:47,772 domogik-butler INFO Configuring name and sex : Нафаня, female
2016-03-03 22:30:47,772 domogik-butler INFO Load minimal brain : /home/sasa/domogik/src/domogik/bin/../butler/brain_minimal.rive
2016-03-03 22:30:47,773 domogik-butler INFO Brain part found : brain_base
2016-03-03 22:30:47,773 domogik-butler INFO - Language found : ru_RU
2016-03-03 22:30:47,804 domogik-butler INFO Brain part found : plugin_weather
2016-03-03 22:30:47,804 domogik-butler INFO - Language found : ru_RU
2016-03-03 22:30:47,813 domogik-butler INFO Learn file found : /var/lib/domogik/resources/butler/butler_learn.rive
2016-03-03 22:30:47,814 domogik-butler INFO Extract tagged features (##feature##) and suggestions (##suggest##) from the rivescript files
2016-03-03 22:30:47,816 domogik-butler INFO 8 feature(s) found
2016-03-03 22:30:47,816 domogik-butler INFO 20 suggestion(s) found
Traceback (most recent call last):
  File "./butler.py", line 574, in <module>
    Butler()
  File "./butler.py", line 162, in __init__
    print(u"*** Welcome in {0} world, your digital assistant! ***".format(self.butler_name))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
2016-03-03 22:31:02,768 domogik-butler DEBUG Send client status : starting
```

**Comment by fritz-smh** [comment]
Could you add to the ticket the butler part of domogik.cfg file ?

**Comment by fritz-smh** [comment]
Fixed on my local repo.
Will push this evening or tomorrow.
