### ISSUE TITLE
newScenario : error not catched

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#262]
Found in stdout : 
```
2016-03-13 12:16:30,244 domogik-scenario.Test - variables 2 WARNING Trigger <bound method ScenarioInstance.generic_trigger of <domogik.scenario.scenario.ScenarioInstance instance at 0x7f87b441c0e0>> called by parameter <domogik.scenario.parameters.cron.CronParameter instance at 0x7f87b4442440>
if self._mapping['test']['e07e6901-2abf-4ace-bef7-0a34f4048180'].evaluate():
    self._mapping['action']['0-c9918ff8-946b-4ae6-88ea-74b7e911b58b'].set_param("value", ("foobar"))
    self._mapping['action']['0-c9918ff8-946b-4ae6-88ea-74b7e911b58b'].set_param("name", ("thename"))
    self._mapping['action']['0-c9918ff8-946b-4ae6-88ea-74b7e911b58b'].do_action({})
    self._mapping['action']['1-55e7f84e-d03e-41aa-9fca-5ada55980ad7'].set_param("message", ("TEST = _{{thename}}_"))
    self._mapping['action']['1-55e7f84e-d03e-41aa-9fca-5ada55980ad7'].do_action({})

2016-03-13 12:16:30,247 domogik-scenario.Test - variables 2 DEBUG Evaluate <domogik.scenario.parameters.cron.CronParameter instance at 0x7f87b4442440> : True
2016-03-13 12:16:30,248 domogik-scenario.Test - variables 2 INFO Variable name=thename
2016-03-13 12:16:30,248 domogik-scenario.Test - variables 2 INFO Variable value=foobar
Exception in thread call trigger <bound method CronTest.cb_trigger of <domogik.scenario.tests.cron.CronTest instance at 0x7f87b44425a8>>:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/dmg/domogik/src/domogik/scenario/tests/abstract.py", line 94, in cb_trigger
    self._trigger(self)
  File "/opt/dmg/domogik/src/domogik/scenario/scenario.py", line 375, in generic_trigger
    st = cond.eval_condition()
  File "/opt/dmg/domogik/src/domogik/scenario/scenario.py", line 323, in eval_condition
    exec(self._compiled_condition)
  File "Scenario Test - variables 2", line 4, in <module>
  File "/opt/dmg/domogik/src/domogik/scenario/actions/set_variable.py", line 51, in do_action
    if val['type'].startswith("sensor.SensorTest."):
TypeError: string indices must be integers, not str

```

**Comment by Cereal2nd** [comment]
the set_bvaraiable action is not supported on newScenario branch
