### ISSUE TITLE
newScenario : error while creating a scenario

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#268]
```
2016-03-15 21:43:29,306 domogik-scenario INFO Create or save scenario : name = '0', id = '0', json = '{"type":"controls_if","id":"CXeRaH*|O;%(XRY0~0(d","IF0":{"type":"logic_compare","id":",BNkb,G3696a?_I2%kd8","OP":"EQ","A":{"type":"time_now.TimeNow","id":"k}bFcJ[Ut_8I*wKED7PA"},"B":{"type":"time_hhmm.TimeHHMMTest","id":"r#mvD-H:V.mL,,1POp-v","time.time":"21:44"}},"DO0":{"type":"log.LogAction","id":"+Fwhx?dfzEjjOJF^w8F]","message":{"type":"text","id":"XUwUkiSx*A5QOJc#d8a[","TEXT":"C'EST L'HEURE"}}}'
2016-03-15 21:43:29,307 domogik-scenario ERROR Exception occured during message processing.
2016-03-15 21:43:29,307 domogik-scenario DEBUG Traceback (most recent call last):
  File "./scenario.py", line 111, in on_mdp_request
    payload = mapping[msg.get_action().split('.')[0]][msg.get_action().split('.')[1]](**msg.get_data())
  File "/opt/dmg/domogik/src/domogik/scenario/manager.py", line 150, in update_scenario
    return self.create_scenario(name, json_input, cid, dis, desc, state, True)
  File "/opt/dmg/domogik/src/domogik/scenario/manager.py", line 197, in create_scenario
    scen = self._db.add_scenario(name, json_input, dis, desc, False)
TypeError: add_scenario() takes exactly 7 arguments (6 given)
```

**Comment by fritz-smh** [comment]
Fixed. Will push later this evening
