### ISSUE TITLE
Domogik on "small" hardware config

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#275]
I'm trying for some time to run Domogik on RPI2.
But impossible to have a running Domogik over 2 days.

After this problem in issue: #258 that I "solve" by reducing external plugins hbeat messges, 
Now I have this message that appears on admin interface for the mq_forwader while in the log all seems ok.

![domogik_mq_error](https://cloud.githubusercontent.com/assets/1257481/13918921/996dce66-ef6a-11e5-8cc6-3bcf0783e94f.jpg)

Another problem, Domogik stop writing sensor data in database after a dozen hours of operation.
In the log xplgw there are no more messages "Storing stat for device ..." but "sensorStoreQueue" continues to grow.
I tried to catch error by launching the xplgw with the "-f" but without success yet.

The storing in database stop near 7:52:

    $ grep Storing core_xplgw.log
    2016-03-21 07:52:12,281 domogik-xplgw INFO Storing stat for device 'Extérieure OW' (15) and sensor 'Temperature' (95) with value '4.3' after conversion.
    2016-03-21 07:52:18,128 domogik-xplgw INFO Storing stat for device 'Extérieure RF' (30) and sensor 'Temperature' (121) with value '3.7' after conversion.
    2016-03-21 07:52:18,751 domogik-xplgw INFO Storing stat for device 'Extérieure RF' (30) and sensor 'Battery' (122) with value '90' after conversion.
    2016-03-21 07:52:19,174 domogik-xplgw INFO Storing stat for device 'Raspberry-Pi voogd' (37) and sensor 'Script Info Temp' (129) with value '36.3' after conversion.
    2016-03-21 07:52:22,563 domogik-xplgw INFO Storing stat for device 'Pluie' (13) and sensor 'Counter diff' (93) with value '412' after conversion.
    2016-03-21 07:52:22,965 domogik-xplgw INFO Storing stat for device 'Pluie' (13) and sensor 'Counter' (92) with value '412' after conversion.
    2016-03-21 07:52:24,213 domogik-xplgw INFO Storing stat for device 'Buanderie' (28) and sensor 'Temperature' (117) with value '11.1' after conversion.
    2016-03-21 07:52:24,747 domogik-xplgw INFO Storing stat for device 'Buanderie' (28) and sensor 'Battery' (118) with value '90' after conversion.
    2016-03-21 07:52:28,566 domogik-xplgw INFO Storing stat for device 'Consommation Elec jour' (38) and sensor 'Script Info Number' (130) with value '2.083' after conversion.
    2016-03-21 07:52:29,652 domogik-xplgw INFO Storing stat for device 'Consommation Eau jour' (35) and sensor 'Script Info Number' (127) with value '9.5' after conversion.
 
But value are still received:

    $ grep Adding core_xplgw.log
    2016-03-21 12:52:22,028 domogik-xplgw DEBUG Adding new message to the sensorQueue, current length = 2
    2016-03-21 12:52:22,324 domogik-xplgw DEBUG Adding new message to the sensorQueue, current length = 3
    2016-03-21 12:52:22,450 domogik-xplgw DEBUG Adding new message to the sensorStoreQueue, current length = 16618
    2016-03-21 12:52:22,906 domogik-xplgw DEBUG Adding new message to the sensorStoreQueue, current length = 16619
    2016-03-21 12:52:23,326 domogik-xplgw DEBUG Adding new message to the sensorQueue, current length = 2
    2016-03-21 12:52:23,406 domogik-xplgw DEBUG Adding new message to the sensorStoreQueue, current length = 16620
    2016-03-21 12:52:23,592 domogik-xplgw DEBUG Adding new message to the sensorQueue, current length = 2
    2016-03-21 12:52:23,625 domogik-xplgw DEBUG Adding new message to the sensorQueue, current length = 3
    2016-03-21 12:52:24,980 domogik-xplgw DEBUG Adding new message to the sensorStoreQueue, current length = 16621
    2016-03-21 12:52:25,464 domogik-xplgw DEBUG Adding new message to the sensorStoreQueue, current length = 16622

I leave rpi2 now to use another hardware configuration with a PC ATOM D525 4 core 2GB RAM.
Unfortunately I find the same problem of sensor data that is not written in databases after a few hours.

THE CPU load of the rpi2 or ATOM is not high for quad core cpu.

    RPI2
     dan@voogd: ~ $ uptime
    1:25:24 p.m. up 2 days, 1:06 p.m., 5 users, load average: 1.32, 1.34, 1.47

    ATOM
     dan@vesta: ~ $ uptime
     1:25:30 p.m. up 2 days, 3:44, 4 users, load average: 1.25, 1.63, 1.53

I use the Domogik/Domogik-mq develop version with the last commits, and it's works without problem on VM (Intel I5 hosting)
but impossible for me to have a stable Domogik on "small" config like rpi2 or ATOM D525.

Can you tell me if you have tested on identical configurations ?
Have you an idea where to find for the cause of this problems?

I do not know what to do now.

**Comment by fritz-smh** [comment]
Issue 1 :
About xplgw, this also happens to me sometimes but I am unable to catch
anything...
I will add some more logs to try identifing the issue. The fact you
reproduce it twice a day is a luck for this ;)

Issue 2 :
About the clients list, when you got this, could you (from
src/domogik/examples/mq-python) :
* launch : python req_client_list.py and give the result
* launch :  python sub_plugin_status.py and see it you got a message for
the status of all components each 15 seconds
* give the result of :  ps -ef | grep dmg_

Thanks

**Comment by fritz-smh** [comment]
About issue 1 (xplgw), when there is no more data storage, do you still see
some "Getting item from the sensorStoreQueue" in logs ?
Thanks,

**Comment by fritz-smh** [comment]
Can you give us a complete part (100 lines) of the xplgw logs when xplgw is
not working anymore ?

**Comment by vdomos** [comment]
I restart Domogik after purge log by mistake, sorry.
it seems to me that there was no "Getting item from the sensorStoreQueue" in logs.
is there a limit for sensorStoreQueue ?

Now, I launch xplgw like that to save all messages, I hope:

    /opt/dmg/domogik/src/domogik/bin/xplgw.py -f > /tmp/xplgw.log 2>&1 &

**Comment by fritz-smh** [comment]
I added/updated some logs today to get something clearing to investigate, I
will push this evening on develop. Stay tuned ;)

**Comment by fritz-smh** [comment]
I pushed some things.
Please clean the logs, restart with them.
When xplgw does not work anymore, put the while log file here (and please also, send it to me by email)

**Comment by vdomos** [comment]
Here is the xplgw.log with this error message when Domogik stop to store sensor:

    2016-03-22 20:22:52,874 domogik-xplgw DEBUG Adding new message to the sensorQueue, current length = 10
    Exception in thread Thread-4:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/opt/dmg/domogik/src/domogik/bin/xplgw.py", line 605, in run
        except Queue.Empty:
    NameError: name 'Queue' is not defined

This log have not your last commit, it's on the second host but still storing data .

[xplgw_vesta.log.gz](https://github.com/domogik/domogik/files/185131/xplgw_vesta.log.gz)
