### ISSUE TITLE
newScenario : error If the scenario name contains unicode

### ISSUE THREAD

**Issue by axboct** [domogik/domogik#280]
```
2016-03-26 16:31:48,589 domogik-scenario DEBUG Send client status : alive
2016-03-26 16:31:52,735 domogik-scenario INFO Create or save scenario : name = '0', id = '0', json = '{"type":"controls_if","id":"CXeRaH*|O;%(XRY0~0(d"}'
2016-03-26 16:31:52,885 domogik-scenario ERROR Creation of a scenario failed. Error is : Traceback (most recent call last):
  File "/home/sasa/domogik/src/domogik/scenario/manager.py", line 205, in create_scenario
    scen = ScenarioInstance(self.log, cid, name, payload, dis, state, self._db)
  File "/home/sasa/domogik/src/domogik/scenario/scenario.py", line 111, in __init__
    self._instanciate()
  File "/home/sasa/domogik/src/domogik/scenario/scenario.py", line 173, in _instanciate
    self._compiled_condition = compile(tmp, "Scenario {0}".format(remove_accents(self._name)), 'exec')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
```

**Comment by fritz-smh** [comment]
Can you test with this ?
If not ok, please put the scenario name here

**Comment by axboct** [comment]
without changes. scenario name in russian Тест
```
2016-03-26 18:15:04,698 domogik-scenario INFO Create or save scenario : name = '0', id = '0', json = '{"type":"controls_if","id":"CXeRaH*|O;%(XRY0~0(d","IF0":{"type":"logic_compare","id":"DjFnStm8m^f`td`~kg`d","OP":"EQ","A":{"type":"sensor.SensorTest.6","id":"45+DYm2xqK?[],P86hUF","usage.usage":"value"},"B":{"type":"DT_Volt","id":"8+0Uunx{U9zcfG,rjZ_T","NUM":"200"}},"DO0":{"type":"log.LogAction","id":"0PppS.S]@.fM[Zy0c)i|","message":{"type":"text","id":"2f[-4vN!o!k-GcA;vpp7","TEXT":"тест"}}}'
2016-03-26 18:15:04,817 domogik-scenario.Тест DEBUG Trigger <bound method ScenarioInstance.generic_trigger of <domogik.scenario.scenario.ScenarioInstance instance at 0x7f119c520a70>> called by parameter <domogik.scenario.parameters.sensor_usage.SensorUsageParameter instance at 0x7f119c4faf80>
2016-03-26 18:15:04,859 domogik-scenario ERROR Creation of a scenario failed. Error is : Traceback (most recent call last):
  File "/home/sasa/domogik/src/domogik/scenario/manager.py", line 205, in create_scenario
    scen = ScenarioInstance(self.log, cid, name, payload, dis, state, self._db)
  File "/home/sasa/domogik/src/domogik/scenario/scenario.py", line 111, in __init__
    self._instanciate()
  File "/home/sasa/domogik/src/domogik/scenario/scenario.py", line 173, in _instanciate
    self._compiled_condition = compile(tmp, u"Scenario {0}".format(remove_accents(self._name)), 'exec')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-12: ordinal not in range(128)
```

**Comment by fritz-smh** [comment]
I pushed a fix, not a perfect one but a working one... 
To improve later on
