### ISSUE TITLE
500: Internal Server Error with new datatype "DT_Motion"

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#281]
I created a new "device type" DT_Motion for the plugin "vdevice", I restarted Domogik but it generates a 500 error after the creation of this device.

I have this error in admin stdout: => UndefinedError: 'dict object' has no attribute u'DT_Motion'

    HTTPServerRequest(protocol='http', host='vesta:40406', method='GET', uri='/client/plugin-vdevice.vesta/dmg_devices/known', version='HTTP/1.1', remote_ip='192.168.0.26', headers={'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'vesta:40406', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0', 'Connection': 'keep-alive', 'Referer': 'http://vesta:40406/client/plugin-vdevice.vesta', 'Cookie': 'session=.eJw9ULtuhDAQ_JXI9RXBgQbpCiIDothFjnjI25wU4AJ2nEhwJ8Cn-_dYFClGmmLnsfNgl-s8LCOLb_N9OLHL1LP4wV4-WczQFiG4rxV0ZtCmbyC6iHQzolABujRCbQLlOgeeQ6tCyMlQnmmoeqMcRMo2BnXCkacb6SQgUfhbyT02pdWOFr0XrFAlDkWxlXkRgagdVjihVavS_YS8Do8eItmoaizmcieBlrR8VZYMtMWKbXpmzxPrlvl6uf2a4ef_BRLvEwngwLPRx-9UpbuXrug-LLZ1UIqaY1VvissQdP8NWvJSng-7-zLMxxzB8w_OcWBz.CdgpMw.2Wu9wXXCxTud8neOQ5wWNsS7utU'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1422, in _execute
        result = self.prepare()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2681, in prepare
        self.fallback(self.request)
      File "/usr/local/lib/python2.7/dist-packages/tornado/wsgi.py", line 277, in __call__
        WSGIContainer.environ(request), start_response)
      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 792, in decorated_view
        return func(*args, **kwargs)
      File "/opt/dmg/domogik/src/domogik/admin/views/clients.py", line 213, in client_devices_known
        error = error)
      File "/opt/dmg/domogik/src/domogik/admin/application.py", line 93, in render_template
        return render_theme_template(user.skin_used, template, **context)
      File "/usr/local/lib/python2.7/dist-packages/flask_themes2/__init__.py", line 138, in render_theme_template
        **context)
      File "/usr/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
        context, ctx.app)
      File "/usr/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
        rv = template.render(context)
      File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
        return self.environment.handle_exception(exc_info, True)
      File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/opt/dmg/domogik/src/domogik/admin/themes/default/templates/client_devices.html", line 1, in top-level template code
        {% extends theme("base/base.html") %}
      File "/opt/dmg/domogik/src/domogik/admin/themes/default/templates/base/base.html", line 1, in top-level template code
        {% block doc -%}
      File "/opt/dmg/domogik/src/domogik/admin/themes/default/templates/base/base.html", line 4, in block "doc"
        {%- block html %}
      File "/opt/dmg/domogik/src/domogik/admin/themes/default/templates/base/base.html", line 42, in block "html"
        {% block body -%}
      File "/opt/dmg/domogik/src/domogik/admin/themes/default/templates/base/base.html", line 48, in block "body"
        {% block content -%}
      File "/opt/dmg/domogik/src/domogik/admin/themes/default/templates/client_devices.html", line 213, in block "content"
        {% if sen.data_type == "DT_Bool" or datatypes[sen.data_type]['parent'] == "DT_Bool" %}
      File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 378, in getitem
        return obj[argument]
    UndefinedError: 'dict object' has no attribute u'DT_Motion'
    ERROR:tornado.access:500 GET /client/plugin-vdevice.vesta/dmg_devices/known (192.168.0.26) 413.75ms
    
    
The datatypes.json file is correct with the DT_Motion type:
    
    ...
        "DT_Bool": {
            "labels": {
                "0": "False",
                "1": "True"
            },
            "childs": [
                "DT_Switch",
                "DT_Enable",
                "DT_Binary",
                "DT_Step",
                "DT_UpDown",
                "DT_OpenClose",
                "DT_Start",
                "DT_State",
                "DT_Motion"
            ]
        },
    ...
        "DT_Motion": {
            "labels": {
                "0": "No motion",
                "1": "Motion"
            },
            "parent": "DT_Bool",
            "childs": []
        },
    ...

I forgot something ?

**Comment by fritz-smh** [comment]
You need to reinstall in order the datatype file to be copied in /var/lib/domogik/resources.
I suppose you forget to do this

**Comment by vdomos** [comment]
you're right, it works better now.
thank,

how to know if a "commit" needs to restart the installation ?

**Comment by tikismoke** [comment]
Datatype or database modification seems to always need it in all case.


Le 26 mars 2016 19:10:12 GMT+01:00, vdomos <notifications@github.com> a écrit :
>you're right, it works better now.
>thank,
>
>how to know if a "commit" needs to restart the installation ?
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/281#issuecomment-201907895

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fritz-smh** [comment]
As tiki said, you need to check the files changed...
