### ISSUE TITLE
UnicodeEncodeError in core_xplgw.log

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#301]
With a new plugin, I have this error in **core_xplgw.log** when storing sensor value.

I don't not understand why the error happens  with the 'same' text string.that has been stored before.
After this error occur,  there is no more storing for this sensor.

In this log, storing is ok pour sensor value :
'De 16h55 à 17h55 : Pas de précipitations'
or
'De 17h00 à 18h00 : Pas de précipitations'

    2016-04-14 16:52:38,994 domogik-xplgw DEBUG Getting item from the store queue, current length = 1, item = '{'sensor_id': u'335', 'value': u'De 16h55 \xe0 17h55 : Pas de pr\xe9cipitations\n', 'time': 1460645558}'
    2016-04-14 16:52:38,994 domogik-xplgw DEBUG DEBUG - BEFORE THE with self._db.session_scope()
    2016-04-14 16:52:38,995 domogik-xplgw DEBUG DEBUG - BEGINNING OF THE with self._db.session_scope()
    2016-04-14 16:52:39,002 domogik-xplgw INFO Storing stat for device 'Prev Pluie LQLY' (236) and sensor 'Rain Hour Info' (335) with value 'De 16h55 à 17h55 : Pas de précipitations
    ' after conversion.
   
    2016-04-14 17:02:39,323 domogik-xplgw DEBUG Getting item from the store queue, current length = 1, item = '{'sensor_id': u'335', 'value': u'De 17h00 \xe0 18h00 : Pas de pr\xe9cipitations\n', 'time': 1460646159}'
    2016-04-14 17:02:39,323 domogik-xplgw DEBUG DEBUG - BEFORE THE with self._db.session_scope()
    2016-04-14 17:02:39,323 domogik-xplgw DEBUG DEBUG - BEGINNING OF THE with self._db.session_scope()
    2016-04-14 17:02:39,331 domogik-xplgw INFO Storing stat for device 'Prev Pluie LQLY' (236) and sensor 'Rain Hour Info' (335) with value 'De 17h00 à 18h00 : Pas de précipitations
    ' after conversion.

But for this above log there is the error, however, it's the same character 'é' !
'De 17h10 à 18h10 : Pas de précipitations'

    2016-04-14 17:07:39,504 domogik-xplgw DEBUG Getting item from the store queue, current length = 1, item = '{'sensor_id': u'335', 'value': u'De 17h10 \xe0 18h10 : Pas de pr\xe9cipitations\n', 'time': 1460646459}'
    2016-04-14 17:07:39,504 domogik-xplgw DEBUG DEBUG - BEFORE THE with self._db.session_scope()
    2016-04-14 17:07:39,504 domogik-xplgw DEBUG DEBUG - BEGINNING OF THE with self._db.session_scope()
    2016-04-14 17:07:39,512 domogik-xplgw INFO Storing stat for device 'Prev Pluie LQLY' (236) and sensor 'Rain Hour Info' (335) with value 'De 17h10 à 18h10 : Pas de précipitations
    ' after conversion.
    2016-04-14 17:07:39,558 domogik-xplgw ERROR Error when adding sensor history : Traceback (most recent call last):
      File "/opt/dmg/domogik/src/domogik/bin/xplgw.py", line 603, in run
    current_date)
      File "/opt/dmg/domogik/src/domogik/common/database.py", line 964, in add_sensor_history
        self.__raise_dbhelper_exception("Error when adding data to sensor history. Sensor id = {0}  | Value = {1}  | Date = {2}. Error is {3}".format(sid, value, date, traceback.format_exc()))
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe0' in position 9: ordinal not in range(128)

**Comment by fritz-smh** [comment]
"This" issue is closed (or should be).
But I am quite sure there is another issue. The issue was in the error message only :)
Now you will get the error message. Please create a new ticket for this one.

**Comment by vdomos** [comment]
The value is return like that in json format:

    u'Pas de pr\xe9cipitations'

it's 'iso-8859-15' encoding,  yes ?

I'dont know if i must use encode or decode function, i alway error with my tests, (c'est vraiment la galère ces encodages :)

I will test tomorrow, too tired with that.
thanks
