### ISSUE TITLE
scenario  utf8 issue

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#306]
```
2016-05-03 22:43:55,818 domogik-scenario.Espace libre DEBUG Scenario 'Espace libre' python generated code :
print('---- Start evaluating ----')
if ( self._mapping['test']['b10191e2-0955-45d6-8a20-8ceae9f03f88'].evaluate() > float("90") ):^M
    if self._mapping['test']['9f4c5228-1e7e-4eff-9be9-c614a5358aca'].evaluate():^M
        self._mapping['action']['0-ebcdb1ce-7e0a-4a73-b3e0-77dfab023c4d'].set_param("value", ("L'espace disque de / sur ambre libre est limité"))^M
        self._mapping['action']['0-ebcdb1ce-7e0a-4a73-b3e0-77dfab023c4d'].do_action()^M
else:^M
    if self._mapping['test']['c36af8df-37f6-4bd1-bd05-ea2f3f017248'].evaluate():^M
        self._mapping['action']['1-92d4547a-f35f-48f3-a382-d8eed1a09507'].do_action()^M

2016-05-03 22:43:55,825 domogik-scenario DEBUG Create scenario instance Espace libre with payload {u'IF0': {u'A': {u'type': u'sensor.SensorTest.58', u'id': u'peG_=@`)u,z3x~N]E-.R', u'usage.usage': u'value'}, u'B': {u'NUM': u'90', u'type': u'math_number', u'id': u'ADHs7t?z4ccR.ZvDwy3s'}, u'type': u'logic_compare', u'id': u'j%MgU#,}bqTgB78%qoJ1', u'OP': u'GT'}, u'ELSE': {u'Run': {u'type': u'pass.PassAction', u'id': u'y2vf.g.r7lcYGzlmi}q]'}, u'type': u'trigger.Hysteresis', u'id': u'[oMR0uX@LW~v*A2#t|E('}, u'elseCount': 1, u'DO0': {u'Run': {u'type': u'command.CommandAction.15', u'id': u'8K]..3#MqQ0{c[re+7gb', u'value': {u'TEXT': u"L'espace disque de / sur ambre libre est limit\xe9", u'type': u'text', u'id': u'53l7`Mk!*`32+zwqCGe)'}}, u'type': u'trigger.Hysteresis', u'id': u'HPv;LJ8SU~gt-ZXm;]Ka'}, u'type': u'controls_if', u'id': u'CXeRaH*|O;%(XRY0~0(d'}
2016-05-03 22:43:55,825 domogik-scenario.Espace libre DEBUG Eval the condition!
2016-05-03 22:43:55,826 domogik-scenario.Espace libre DEBUG Evaluate SensorTest '58' in mode 'value' to '91.0'. Type is '<type 'float'>'
2016-05-03 22:43:56,013 domogik-scenario.Espace libre INFO Do an action...
2016-05-03 22:43:56,013 domogik-scenario.Espace libre DEBUG Preprocessing on parameters...
2016-05-03 22:43:56,014 domogik-scenario.Espace libre DEBUG Parameters before processing : {'value': "L'espace disque de / sur ambre libre est limit\xc3\xa9"}
2016-05-03 22:43:56,044 domogik-scenario.Espace libre ERROR Error while evaluating condition '<code object <module> at 0x7f675c462cb0, file "Scenario Espace libre", line 1>'. Error is : Traceback (most recent call last):
  File "/opt/dmg/domogik/src/domogik/scenario/scenario.py", line 404, in eval_condition
    exec(self._compiled_condition)
  File "Scenario Espace libre", line 5, in <module>
  File "/opt/dmg/domogik/src/domogik/scenario/actions/command.py", line 53, in do_action
    self.log.debug(u"Preprocess for param : key={0}, typeofvalue={1}, value={2}".format(key, type(self._params[key]), self._params[key]))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 46: ordinal not in range(128)

2016-05-03 22:43:56,106 domogik-scenario ERROR Creation of a scenario failed. Error is : Traceback (most recent call last):
  File "/opt/dmg/domogik/src/domogik/scenario/manager.py", line 208, in create_scenario
    self._instances[cid]['instance'].eval_condition()
  File "/opt/dmg/domogik/src/domogik/scenario/scenario.py", line 404, in eval_condition
    exec(self._compiled_condition)
  File "Scenario Espace libre", line 5, in <module>
  File "/opt/dmg/domogik/src/domogik/scenario/actions/command.py", line 53, in do_action
    self.log.debug(u"Preprocess for param : key={0}, typeofvalue={1}, value={2}".format(key, type(self._params[key]), self._params[key]))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 46: ordinal not in range(128)

2016-05-03 22:44:03,849 domogik-scenario DEBUG Send client status : alive
```

**Comment by fritz-smh** [comment]
Fixed ln my local repo.
