### ISSUE TITLE
sqlalchemy error on creating device from admin

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#313]
On Creating  device there is this issue on core_dbmgr.log

Branch develop up to date (08/06/2016)
SQLAlchemy==1.0.11
SQLAlchemy-Utils==0.32.5
```
2016-06-08 00:28:11,488 domogik-dbmgr DEBUG MQ Request received : <MQMessage(action=device.create, data='{u'data': {u'xpl_stats': {}, u'name': u'Volet cuisine', u'reference': u'Qubino -- ZMNHCDx Flush Shutter', u'xpl': [], u'xpl_commands': {}, u'global': [{u'key': u'networkid', u'type': u'string', u'description': u'Zwave network name if refered in controller node or Openzwave Home ID', u'value': u'Maison'}, {u'description': u'Zwave node id', u'max_value': 255, u'min_value': 1, u'value': u'2', u'key': u'node', u'type': u'integer'}, {u'description': u'Zwave node instance id', u'max_value': 255, u'min_value': 1, u'value': u'1', u'key': u'instance', u'type': u'integer'}], u'device_type': u'ozwave.energy-k_energy-previous-reading-k_level_power_switch__bright_dim_switch', u'client_id': u'plugin-ozwave.vmdevubuntu16', u'description': u'Controle du volet'}}')>
2016-06-08 00:28:11,615 domogik-dbmgr DEBUG ['device.create.result', '{"status": false, "reason": "An error occured while adding the device in database. Please check the file dbmgr.log for more informations"}']
2016-06-08 00:28:11,627 domogik-dbmgr ERROR Error while processing request. Message is : <MQMessage(action=device.create, data='{u'data': {u'xpl_stats': {}, u'name': u'Volet cuisine', u'reference': u'Qubino -- ZMNHCDx Flush Shutter', u'xpl': [], u'xpl_commands': {}, u'global': [{u'key': u'networkid', u'type': u'string', u'description': u'Zwave network name if refered in controller node or Openzwave Home ID', u'value': u'Maison'}, {u'description': u'Zwave node id', u'max_value': 255, u'min_value': 1, u'value': u'2', u'key': u'node', u'type': u'integer'}, {u'description': u'Zwave node instance id', u'max_value': 255, u'min_value': 1, u'value': u'1', u'key': u'instance', u'type': u'integer'}], u'device_type': u'ozwave.energy-k_energy-previous-reading-k_level_power_switch__bright_dim_switch', u'client_id': u'plugin-ozwave.vmdevubuntu16', u'description': u'Controle du volet'}}')>. Error is : Traceback (most recent call last):
  File "/home/admdomo/domogik/src/domogik/bin/dbmgr.py", line 147, in on_mdp_request
    self._mdp_reply_sensor_history(msg)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/admdomo/domogik/src/domogik/common/database.py", line 178, in session_scope
    self.__session.commit()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 813, in commit
    self.transaction.commit()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 390, in commit
    self._assert_active(prepared_ok=True)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
    % self._rollback_exception
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.DataError) (1406, u"Data too long for column 'reference' at row 1") [SQL: u'INSERT INTO core_device (name, description, reference, device_type_id, client_id, client_version) VALUES (%(name)s, %(description)s, %(reference)s, %(device_type_id)s, %(client_id)s, %(client_version)s)'] [parameters: {'name': u'Volet cuisine', 'reference': u'Qubino -- ZMNHCDx Flush Shutter', 'client_id': u'plugin-ozwave.vmdevubuntu16', 'device_type_id': u'ozwave.energy-k_energy-previous-reading-k_level_power_switch__bright_dim_switch', 'client_version': u'0.5.1', 'description': u'Controle du volet'}]

2016-06-08 00:28:20,155 domogik-dbmgr DEBUG Send client status : alive

```

**Comment by fritz-smh** [comment]
Data too long for column 'reference'


I will add some truncate functionnality to avoid this error.
