### ISSUE TITLE
[develop] DB upgrade error (alembic)

### ISSUE THREAD

**Issue by overload08** [domogik/domogik#326]
Hello!
Je tente d'upgrader de 0.4.2 vers 0.5.

J'ai a priori une erreur lors de l'upgrade de la DB : 

INFO  [alembic.runtime.migration] Context impl MySQLImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 1840cdc9f1da -> 49d3ea7fccfd, Finish datatbase model started in 0.4
INFO  [alembic.runtime.migration] Running upgrade 49d3ea7fccfd, 14ebd5a1ef73 -> 1f83a07281da, merge 0.4.1 and sensorupgrades
INFO  [alembic.runtime.migration] Running upgrade 1f83a07281da, 3952bcc21640 -> 34f2d2258b7d, megre 0.5.0
INFO  [alembic.runtime.migration] Running upgrade 34f2d2258b7d -> 2e6c120aa69a, Upgrade field length
INFO  [alembic.runtime.migration] Running upgrade 2e6c120aa69a -> a2a3015badf, Upgrade float precission
INFO  [alembic.runtime.migration] Running upgrade a2a3015badf -> b16c5714678, Add state field in scenarios
INFO  [alembic.runtime.migration] Running upgrade b16c5714678 -> 404f46a359dc, add anonymous
========= TRACEBACK =============
Traceback (most recent call last):
  File "./install.py", line 518, in install
    dbi.install_or_upgrade_db(args.skip_database_backup)
  File "/usr/local/lib/python2.7/dist-packages/domogik/install/db_install.py", line 150, in install_or_upgrade_db
    command.upgrade(self.alembic_cfg, "head")
  File "/usr/lib/python2.7/dist-packages/alembic/command.py", line 174, in upgrade
    script.run_env()
  File "/usr/lib/python2.7/dist-packages/alembic/script/base.py", line 407, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/lib/python2.7/dist-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/lib/python2.7/dist-packages/alembic/util/compat.py", line 79, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "src/domogik/install/alembic/env.py", line 79, in <module>
    run_migrations_online()
  File "src/domogik/install/alembic/env.py", line 72, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/lib/python2.7/dist-packages/alembic/runtime/environment.py", line 797, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/lib/python2.7/dist-packages/alembic/runtime/migration.py", line 312, in run_migrations
    step.migration_fn(**kw)
  File "/opt/dmg/domogik/src/domogik/install/alembic/versions/404f46a359dc_add_anonymous.py", line 20, in upgrade
    db.add_user_account_with_person('Anonymous', 'Anonymous', 'Rest', 'Anonymous')
  File "/usr/local/lib/python2.7/dist-packages/domogik/common/database.py", line 1249, in add_user_account_with_person
    return self.add_user_account(a_login, person.id, a_password, a_is_admin, a_skin_used)
  File "/usr/local/lib/python2.7/dist-packages/domogik/common/database.py", line 1220, in add_user_account
    ).filter_by(login=ucode(a_login)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2634, in first
    ret = list(self[0:1])
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2457, in __getitem__
    return list(res)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 837, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1021, in _read_query_result
    result.read()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 1304, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 983, in _read_packet
    packet.check_error()
  File "/usr/local/lib/python2.7/dist-packages/pymysql/connections.py", line 395, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python2.7/dist-packages/pymysql/err.py", line 102, in raise_mysql_exception
    raise errorclass(errno, errval)
InternalError: (pymysql.err.InternalError) (1054, u"42S22Unknown column 'core_user_account.lock_edit' in 'field list'") [SQL: u'SELECT core_user_account.id AS core_user_account_id, core_user_account.login AS core_user_account_login, core_user_account.password AS core_user_account_password, core_user_account.person_id AS core_user_account_person_id, core_user_account.is_admin AS core_user_account_is_admin, core_user_account.skin_used AS core_user_account_skin_used, core_user_account.lock_edit AS core_user_account_lock_edit, core_user_account.lock_delete AS core_user_account_lock_delete \nFROM core_user_account \nWHERE core_user_account.login = %(login_1)s \n LIMIT %(param_1)s'] [parameters: {u'login_1': u'Anonymous', u'param_1': 1}]

=================================
ERROR [root] (<class 'sqlalchemy.exc.InternalError'>, InternalError('(pymysql.err.InternalError) (1054, u"42S22Unknown column \'core_user_account.lock_edit\' in \'field list\'")',), <traceback object at 0x7fe1d903bef0>)
 ==> (<class 'sqlalchemy.exc.InternalError'>, InternalError('(pymysql.err.InternalError) (1054, u"42S22Unknown column \'core_user_account.lock_edit\' in \'field list\'")',), <traceback object at 0x7fe1d903bef0>)

Après vérification, il me manque effectivement la colonne 'lock_edit'.

Y a-t-il quelque chose à lancer avant ?

**Comment by overload08** [comment]
J'ai dû le faire à la mano, encore une erreur Duplicate column name \'lock_delete\'".

Revoir le script d'install ^^

**Comment by Cereal2nd** [comment]
I found the error, but i don't have a quick fix ...

the problem is in 404f46a359dc_add_anonymous.py
as this is not using alembic code this is triggering the error

**Comment by overload08** [comment]
No problem, my upgrade is fine now.
You can leave this issue opened until it isn't resolved ;)

**Comment by phhorrein** [comment]
Hi,
I encountered the same problem when upgrading from 0.4.2 to 0.5. I attached my (almost) anomimous database to the ticket. 

The problem seems to be in alembic: the revision which adds the lock_xxx columns to the table (4db99a451791) comes after a revision which adds a record to the DB (404f46a359dc) : 
`alembic history -rcurrent:head` 
returns : 
```
2f736b443fd2 -> 307d90982e2a (head), Add info_changed field`
a849c7073f8 -> 2f736b443fd2, extend device_type_id #323
4db99a451791 -> a849c7073f8, Change some columns size
2269ae8c2bc7 -> 4db99a451791, Add lock columns to account table
481f304ccc1a -> 2269ae8c2bc7, remove trigger mode, increased state
38b868f7501a -> 481f304ccc1a, Increase last value in sensor and sensorhistory
404f46a359dc -> 38b868f7501a, Add trigegr_mode to scenario
b16c5714678 -> 404f46a359dc, add anonymous
a2a3015badf -> b16c5714678, Add state field in scenarios
```


[domogik_anon.txt](https://github.com/domogik/domogik/files/539991/domogik_anon.txt)

Freki

**Comment by phhorrein** [comment]
OK, fixing the alembic order fixed the install process. I attach a patch which does just that. 

Freki
[fix_db_upgrade.txt](https://github.com/domogik/domogik/files/540033/fix_db_upgrade.txt)

**Comment by fritz-smh** [comment]
@Cereal2nd does it seems ok for you ?
