### ISSUE TITLE
Python psutil depreciate function up to 2.0.0 make issue at plugin start-up

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#331]
From domogik dependencies : 
          psutil >= 0.1.3

But since psutil 2.0.0 Released at March 10, 2014  : 
p.get_cpu_percent()	 -->  p.cpu_percent()
https://allmychanges.com/p/python/psutil/

see log error for psutil==3.4.2  at plugin start-up

```
2016-09-05 15:42:49,615 domogik-notify INFO Read the json file and validate id
Exception in thread send_process_info:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/admdomo/domogik/src/domogik/common/processinfo.py", line 78, in start
    self._get_values()
  File "/home/admdomo/domogik/src/domogik/common/processinfo.py", line 91, in _get_values
    cpu_percent = round(self.p.get_cpu_percent(), 1)
AttributeError: 'Process' object has no attribute 'get_cpu_percent'

```

**Comment by fritz-smh** [comment]
This is related to something I developped a while ago... and reactivated a
few weeks ago.
I will upgrade this.

Thanks for the information !
