### ISSUE TITLE
admin exception

### ISSUE THREAD

**Issue by Cereal2nd** [domogik/domogik#333]
2016-09-09 14:21:00,645 domogik-admin DEBUG locale : ('en_US', 'UTF-8')
Exception in thread send_process_info:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/cereal/domogik/src/domogik/common/processinfo.py", line 78, in start
    self._get_values()
  File "/home/cereal/domogik/src/domogik/common/processinfo.py", line 91, in _get_values
    cpu_percent = round(self.p.get_cpu_percent(), 1)
AttributeError: 'Process' object has no attribute 'get_cpu_percent'

**Comment by Cereal2nd** [comment]
duplicate ....
