### ISSUE TITLE
Variables Item doesn't work (0.5)

### ISSUE THREAD

**Issue by cedric-bollini** [domogik/domogik#335]
I try to used "Variables Item" but it doesn't work

2016-09-12 22:20:50,885 domogik-scenario.Couloir Haut DEBUG Evaluate current time to '1340' minutes. Type is '<type 'int'>'
2016-09-12 22:20:50,885 domogik-scenario.Couloir Haut INFO 1340
2016-09-12 22:20:50,885 domogik-scenario.Couloir Haut DEBUG Evaluate current time to '1340' minutes. Type is '<type 'int'>'

and after

2016-09-12 22:25:37,985 domogik-scenario.Couloir Haut ERROR Error while evaluating condition '<code object <module> at 0x7f76200a1f30, file "Scenario Couloir Haut", line 1>'. Error is : Traceback (most recent call last):
  File "/opt/dmg/domogik/src/domogik/scenario/scenario.py", line 404, in eval_condition
    exec(self._compiled_condition)
  File "Scenario Couloir Haut", line 10, in <module>
NameError: name 'heure' is not defined

Scenario: https://snag.gy/DjSLMW.jpg

**Comment by tikismoke** [comment]
On set_value.py Line 62. They're is a to-do for non sensor value. As I understood the code before for now you can only set a value with a sensor value. Not another value like time.

That's why you have the error.
