### ISSUE TITLE
process_info issue

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#336]
Exception in thread send_process_info:
Traceback (most recent call last):
```
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/domogik/src/domogik/common/processinfo.py", line 78, in start
    self._get_values()
  File "/home/domogik/src/domogik/common/processinfo.py", line 93, in _get_values
    memory_total_phymem = round(psutil.TOTAL_PHYMEM / (1024 * 1024), 0)
AttributeError: 'module' object has no attribute 'TOTAL_PHYMEM'

```

**Comment by tikismoke** [comment]
Seems solved by https://github.com/domogik/domogik/commit/33d9b9db7f25b288321f7788e70fe77998541700

**Comment by tikismoke** [comment]
Now answer looks like this:

`domogik-admin DEBUG Process informations|python_version=2.7|psutil_version=4.3.1|domogik_version=0.5.0|client=plugin-admin.domogik|client_version=None|pid=23524|cpu_percent_usage=1.0|memory_total=16084.0|memory_percent_usage=0.3|memory_rss=52.0|memory_vsz=301.0|num_threads=7|num_file_descriptors_used=40|
`
