### ISSUE TITLE
Error when adding a devices (plugin weather)

### ISSUE THREAD

**Issue by titoko** [domogik/domogik#353]
when adding a devices in the plugin weather I've got a weird issue resulting to an error 500 and then can't access the domogik devices tab!

the log show this : 
==> domogik/core_dbmgr.log <==
2016-10-11 22:39:52,529 domogik-dbmgr ERROR Error while processing request. Message is : <MQMessage(action=device.create, data='{u'data': {u'xpl_stats': {u'forecast_day_3': [], u'current_wind_speed': [], u'current_last_updated': [], u'current_visibility': [], u'current_humidity': [], u'forecast_day_4': [], u'current_feels_like': [], u'current_temperature': [], u'current_sunrise': [], u'current_text': [], u'current_wind_direction': [], u'forecast_day_2': [], u'forecast_day_1': [], u'forecast_day_0': [], u'current_station': [], u'current_sunset': [], u'current_code': [], u'current_barometer_value': []}, u'name': u'lyon.weather', u'reference': u'w.lyon', u'xpl': [{u'key': u'device', u'type': u'string', u'description': u'Location code. Example for Paris : 615702', u'value': u'615702'}], u'xpl_commands': {}, u'global': [], u'device_type': u'weather.weather', u'client_id': u'plugin-weather.titoko', u'description': u'weather.lyon'}}')>. Error is : Traceback (most recent call last):
  File "/opt/dmg/domogik/src/domogik/bin/dbmgr.py", line 133, in on_mdp_request
    self._mdp_reply_devices_create_result(msg)
  File "/opt/dmg/domogik/src/domogik/bin/dbmgr.py", line 618, in _mdp_reply_devices_create_result
    self.log.debug(msg.get())
  File "/opt/dmg/domogik-mq/src/domogikmq/message.py", line 67, in get
    stack.append( json.dumps(self._data).encode() )
  File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2016, 10, 11, 22, 39, 51) is not JSON serializable

**Comment by Cereal2nd** [comment]
this one is mine, i'll look into it

**Comment by titoko** [comment]
Find a workaroud but not sure this is the best way of solving this.
You add a datetime column in the device tables but datetime are not json serializable so we just need to convert it to string when we return the json in the get_device function (in common/database.py line 426)

**Comment by tikismoke** [comment]
Also look at the admin we could no more modify an existing device. The field update_info is always required.
