### ISSUE TITLE
undefined symbol: SSLv3_method

### ISSUE THREAD

**Issue by ferllings** [domogik/domogik#398]
```
$ sudo dmg_package --upgrade https://github.com/fritz-smh/domogik-plugin-rfxcom/archive/1.68.3.zip
Traceback (most recent call last):
  File "/usr/bin/dmg_package", line 11, in <module>
    load_entry_point('Domogik', 'console_scripts', 'dmg_package')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2627, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2287, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2293, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/cedric/domogik/domogik.repository.git/src/domogik/bin/package.py", line 58, in <module>
    import OpenSSL
  File "/usr/lib/python2.7/site-packages/pyOpenSSL-0.13-py2.7-linux-i686.egg/OpenSSL/__init__.py", line 41, in <module>
    from OpenSSL import rand, SSL
ImportError: /usr/lib/python2.7/site-packages/pyOpenSSL-0.13-py2.7-linux-i686.egg/OpenSSL/SSL.so: undefined symbol: SSLv3_method
```

The problem is caused by the ArchLinux OpenSSL package being built without SSLv3 support, as of this commit: https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/openssl&id=4b82ed4285c7cb76caf6d75a015c5a7542c625d1

**Comment by fritz-smh** [comment]
Additionnal info : it s on ArchLinux

**Comment by fritz-smh** [comment]
Can you try some of the hints from here :
http://stackoverflow.com/questions/28987891/patch-pyopenssl-for-sslv3-issue

I don't really see how to fix this right now in domogik :(

**Comment by fritz-smh** [comment]
Moved in 0.6

**Comment by fritz-smh** [comment]
Closing for now as there were a lot of changes in ssl the last monthes...
If needed, reopen it.
