### ISSUE TITLE
An error occured while adding the device in database

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#412]
I'm not sure it's the same issue #411:

I have this error randomly when I created a new device on different plugin (0.5-hotfix branch):
(1062, u"Duplicate entry '0-value' for key 'PRIMARY'")

    2016-12-29 17:04:02,142 domogik-dbmgr DEBUG ['device.create.result', '{"status": false, "reason": "An error occured while adding the device in database. Please check the file dbmgr.log for more informations"}']
    2016-12-29 17:04:02,145 domogik-dbmgr ERROR Error while processing request. Message is : <MQMessage(action=device.create, data='{u'data': {u'xpl_stats': {}, u'name': u'Temp Ext Min', u'reference': u'', u'xpl': [], u'xpl_commands': {}, u'global': [{u'default': u'0', u'key': u'value', u'type': u'integer', u'description': u"Initial value (number) for the device's sensor", u'value': u'99'}], u'device_type': u'vdevice.number', u'client_id': u'plugin-vdevice.hadesd', u'description': u''}}')>. Error is : Traceback (most recent call last):
      File "/opt/dmg/domogik/src/domogik/bin/dbmgr.py", line 148, in on_mdp_request
        self._mdp_reply_sensor_history(msg)
      File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
        self.gen.next()
      File "/opt/dmg/domogik/src/domogik/common/database.py", line 180, in session_scope
        self.__session.commit()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 874, in commit
        self.transaction.commit()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 459, in commit
        self._assert_active(prepared_ok=True)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
        % self._rollback_exception
    InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.IntegrityError) (1062, u"Duplicate entry '0-value' for key 'PRIMARY'") [SQL: u'INSERT INTO core_device_param (device_id, `key`, value, type) VALUES (%(device_id)s, %(key)s, %(value)s, %(type)s)'] [parameters: {'type': u'integer', 'key': u'value', 'value': u'99', 'device_id': 16}]

    2016-12-29 17:16:40,431 domogik-dbmgr DEBUG ['device.create.result', '{"status": false, "reason": "An error occured while adding the device in database. Please check the file dbmgr.log for more informations"}']
    2016-12-29 17:16:40,432 domogik-dbmgr ERROR Error while processing request. Message is : <MQMessage(action=device.create, data='{u'data': {u'xpl_stats': {u'ping': []}, u'name': u'wopr', u'reference': u'', u'xpl': [{u'key': u'device', u'type': u'string', u'description': u'The ip or name of the element you want to ping', u'value': u'192.168.0.40'}], u'xpl_commands': {}, u'global': [{u'key': u'interval', u'type': u'integer', u'description': u'Interval in seconds between 2 ping actions.', u'value': u'300'}], u'device_type': u'ping.ping', u'client_id': u'plugin-ping.hadesd', u'description': u''}}')>. Error is : Traceback (most recent call last):
      File "/opt/dmg/domogik/src/domogik/bin/dbmgr.py", line 148, in on_mdp_request
        self._mdp_reply_sensor_history(msg)
      File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
        self.gen.next()
      File "/opt/dmg/domogik/src/domogik/common/database.py", line 180, in session_scope
        self.__session.commit()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 874, in commit
        self.transaction.commit()
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 459, in commit
        self._assert_active(prepared_ok=True)
      File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
        % self._rollback_exception
    InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.IntegrityError) (1062, u"Duplicate entry '0-interval' for key 'PRIMARY'") [SQL: u'INSERT INTO core_device_param (device_id, `key`, value, type) VALUES (%(device_id)s, %(key)s, %(value)s, %(type)s)'] [parameters: {'type': u'integer', 'value': u'300', 'key': u'interval', 'device_id': 20}]

**Comment by vdomos** [comment]
The 'id' in  core_device_param is alway '0':

    mysql> select * from core_device_param ;
    +----+-----------+------------+------------------------+---------+
    | id | device_id | key        | value                  | type    |
    +----+-----------+------------+------------------------+---------+
    |  0 |         2 | device     | 1D.61BF0D000000        | string  |
    |  0 |         2 | interval   | 60                     | integer |
    |  0 |         2 | properties | counters.A             | choice  |
    |  0 |         1 | qos        | 0                      | string  |
    |  0 |         1 | topic      | jsensor/teleinfo/power | string  |
    |  0 |        14 | value      | 99                     | integer |
    +----+-----------+------------+------------------------+---------+
    6 rows in set (0.00 sec)

**Comment by Cereal2nd** [comment]
Can you show me the show create table of that table?

**Comment by vdomos** [comment]
Where can I find it ?
 It's in Domogik install ?

**Comment by Cereal2nd** [comment]
No in mysql. Do a 'show create table core_device_param'

Maikel

**Comment by vdomos** [comment]
core_device_param | CREATE TABLE `core_device_param` (
      `id` int(11) NOT NULL,
      `device_id` int(11) NOT NULL,
      `key` varchar(32) NOT NULL,
      `value` varchar(255) DEFAULT NULL,
      `type` varchar(32) DEFAULT NULL,
      PRIMARY KEY (`id`,`key`),
      KEY `device_id` (`device_id`),
      CONSTRAINT `core_device_param_ibfk_1` FOREIGN KEY (`device_id`) REFERENCES `core_device` (`id`) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8


On a another host, I have that:
AUTO_INCREMENT is missing !

    core_device_param | CREATE TABLE `core_device_param` (
      `id` int(11) NOT NULL AUTO_INCREMENT,
      `device_id` int(11) NOT NULL,
      `key` varchar(32) NOT NULL,
      `value` varchar(255) DEFAULT NULL,
      `type` varchar(32) DEFAULT NULL,
      PRIMARY KEY (`id`,`key`),
      KEY `device_id` (`device_id`),
      CONSTRAINT `core_device_param_ibfk_1` FOREIGN KEY (`device_id`) REFERENCES `core_device` (`id`) ON DELETE CASCADE
    ) ENGINE=InnoDB AUTO_INCREMENT=224 DEFAULT CHARSET=utf8

**Comment by Cereal2nd** [comment]
indeed, are both hosts a fresh install or are some an upgrade from 0.3? or 0.4?

**Comment by vdomos** [comment]
The issue host is  a fresh install since a week.
The other is installed since april.
The both from branch develop, no upgrade from 0.3 or 04.

**Comment by vdomos** [comment]
I do
- drop all domogik database tables
- git pull in /opt/dmg/domogik (0.5-hotfix branch)
- run python install.py

The create table core_device_param` have still  AUTO_INCREMENT  missing !

    core_device_param | CREATE TABLE `core_device_param` (
      `id` int(11) NOT NULL,
      `device_id` int(11) NOT NULL,
      `key` varchar(32) NOT NULL,
      `value` varchar(255) DEFAULT NULL,
      `type` varchar(32) DEFAULT NULL,
      PRIMARY KEY (`id`,`key`),
      KEY `device_id` (`device_id`),
      CONSTRAINT `core_device_param_ibfk_1` FOREIGN KEY (`device_id`) REFERENCES `core_device` (`id`) ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8

**Comment by Cereal2nd** [comment]
what sql version are you using?

**Comment by vdomos** [comment]
Server version: 5.5.53-0+deb8u1 (Debian)


2016-12-31 13:11 GMT+01:00 Maikel Punie <notifications@github.com>:

**Comment by vdomos** [comment]
it's ok for me after the today's update.
thanks
