### ISSUE TITLE
NoneType Object error when trying access to login to admin page

### ISSUE THREAD

**Issue by Cquad** [domogik/domogik#458]
I have launch domogik with docker repo, and when I trying to login with domogik/domopass to admin logon page I have the following error :

```
2017-02-16 19:17:08,522 domogik.admin.application ERROR Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1632, in finalize_request
    response = self.process_response(response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1858, in process_response
    self.save_session(ctx.session, response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 924, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/usr/local/lib/python2.7/dist-packages/Flask_Session-0.3.0-py2.7.egg/flask_session/sessions.py", line 357, in save_session
    session_id = self._get_signer(app).sign(want_bytes(session.sid))
AttributeError: 'NoneType' object has no attribute 'sign'
```

**Comment by tikismoke** [comment]
Try Domogik/123

**Comment by cereal2nd** [comment]
This means you don't have a secret_key set in your config file.

**Comment by cereal2nd** [comment]
see https://github.com/fengsp/flask-session/issues/66

**Comment by cereal2nd** [comment]
reopen if the problem is still there after the secret key was added to the config file
