### ISSUE TITLE
Develop, Queryconfig fail sometime on request plugin.start.do 

### ISSUE THREAD

**Issue by Nico0084** [domogik/domogik#466]
Sometime manager get error on plugin.start.do.
not sure it's a queryconfig issue, perhaps a ZMQ issue ?

```
2017-03-02 23:39:37,407 domogik-manager DEBUG MQ Request received : <MQMessage(action=plugin.start.do, data='{u'host': u'vmdevubuntu16', u'type': u'plugin', u'name': u'rfplayer'}')>
2017-03-02 23:39:37,409 domogik-manager INFO Plugin startup request : <MQMessage(action=plugin.start.do, data='{u'host': u'vmdevubuntu16', u'type': u'plugin', u'name': u'rfplayer'}')>
2017-03-02 23:39:37,410 domogik-manager INFO Looking for launched instances of 'rfplayer'
2017-03-02 23:39:37,675 domogik-manager INFO No existing process.
2017-03-02 23:39:37,678 domogik-manager INFO Request query config for client rfplayer : key test_mode
2017-03-02 23:39:37,688 domogik-manager ERROR Error while processing MQ message : '<MQMessage(action=plugin.start.do, data='{u'host': u'vmdevubuntu16', u'type': u'plugin', u'name': u'rfplayer'}')>'. Error is : Traceback (most recent call last):
  File "/home/admdomo/domogik/src/domogik/bin/manager.py", line 486, in on_mdp_request
    self._mdp_reply_plugin_start(msg)
  File "/home/admdomo/domogik/src/domogik/bin/manager.py", line 602, in _mdp_reply_plugin_start
    pid = self._plugins[name].start()
  File "/home/admdomo/domogik/src/domogik/bin/manager.py", line 1315, in start
    test_mode = self._config.query(self.type, self.name, "test_mode")
  File "/home/admdomo/domogik/src/domogik/common/queryconfig.py", line 57, in query
    return self.qry.query(type, name, key)
  File "/home/admdomo/domogik/src/domogik/common/queryconfig.py", line 122, in query
    ret = self.cli.request('admin', msg.get(), timeout=QUERY_CONFIG_WAIT)
  File "/home/admdomo/domogik-mq/src/domogikmq/reqrep/client.py", line 120, in request
    ret = self.rawrequest( service, msg, timeout)
  File "/home/admdomo/domogik-mq/src/domogikmq/reqrep/client.py", line 101, in rawrequest
    self.socket.send_multipart(to_send)
  File "/home/admdomo/domogik-mq/src/domogikmq/socket.py", line 23, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/zmq/sugar/socket.py", line 329, in send_multipart
    self.send(msg, SNDMORE|flags, copy=copy, track=track)
  File "/home/admdomo/domogik-mq/src/domogikmq/socket.py", line 23, in wrapper
    return f(self, *args, **kwargs)
  File "zmq/backend/cython/socket.pyx", line 617, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:6625)
  File "zmq/backend/cython/socket.pyx", line 664, in zmq.backend.cython.socket.Socket.send (zmq/backend/cython/socket.c:6363)
  File "zmq/backend/cython/socket.pyx", line 199, in zmq.backend.cython.socket._send_copy (zmq/backend/cython/socket.c:2492)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:7535)
    raise ZMQError(errno)
ZMQError: Operation cannot be accomplished in current state

2017-03-02 23:39:37,696 domogik-manager INFO Request query config for client rfxcom : key *
2017-03-02 23:39:37,719 domogik-manager DEBUG Package available : plugin_weather
2017-03-02 23:39:37,722 domogik-manager DEBUG Package plugin-weather : read the json file and validate it
2017-03-02 23:39:37,772 domogik-manager DEBUG Query config : successfull response : <MQMessage(action=config.result, data='{u'status': True, u'name': u'rfxcom', u'data': {u'device': u'/dev/rfxcom', u'configured': True}, u'host': u'vmdevubuntu16', u'reason': u'', u'key': u'*', u'type': u'plugin'}')>

```

**Comment by cereal2nd** [comment]
should be fixed with: https://github.com/domogik/domogik/commit/8e5288f2265a8873788c12dac5969d31405586af
