### ISSUE TITLE
Develop: 500: Internal Server Error in dmg_devices/edit

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#468]
I update a Domogik from 0.5hotfix to develop today and I have this error when editing Device:
500: Internal Server Error

In this menu:

![screenshot_20170304_171934](https://cloud.githubusercontent.com/assets/1257481/23580296/c47b92cc-00fe-11e7-802b-f8aa4ce566b4.png)

Same error in all plugins/devices
No problem when editing "Global parameters" or "Sensors".

Error in admin stderr:

    --------------------------------------------------------------------------------
    INFO in application [/opt/dmg/domogik/src/domogik/admin/application.py:94]:
    http request for /client/plugin-weather.vesta/dmg_devices/edit/31 received
    --------------------------------------------------------------------------------
    2017-03-04 17:10:38,076 domogik.admin.application INFO http request for /client/plugin-weather.vesta/dmg_devices/edit/31 received
    /opt/dmg/domogik/src/domogik/admin/views/clients.py:434: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
      form = MyForm(request.form, device)
    ERROR:tornado.application:Uncaught exception GET /client/plugin-weather.vesta/dmg_devices/edit/31 (192.168.0.5)
    HTTPServerRequest(protocol='http', host='vesta:40406', method='GET', uri='/client/plugin-weather.vesta/dmg_devices/edit/31', version='HTTP/1.1', remote_ip='192.168.0.5', headers={'Accept-Language': 'fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': 'vesta:40406', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36', 'Connection': 'keep-alive', 'Referer': 'http://vesta:40406/client/plugin-weather.vesta/dmg_devices/known', 'Cookie': 'user="2|1:0|10:1488631768|4:user|8:YWRtaW4=|c94619b657123ebab3331b075561464efb19c6a91ccf10d0778c717fb5c403ce"; i18next=fr-FR; session=0bd4798f-4667-49b8-b87b-3bb3607c7f34.SGG4Nee9pKzzo_jKofWitPQAwmg', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/web.py", line 1446, in _execute
        result = self.prepare()
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/web.py", line 2706, in prepare
        self.fallback(self.request)
      File "/usr/local/lib/python2.7/dist-packages/tornado-4.4.2-py2.7-linux-x86_64.egg/tornado/wsgi.py", line 277, in __call__
        WSGIContainer.environ(request), start_response)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__
        return self.wsgi_app(environ, start_response)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
        response = self.handle_exception(e)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
        response = self.full_dispatch_request()
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
        return func(*args, **kwargs)
      File "/opt/dmg/domogik/src/domogik/admin/views/clients.py", line 434, in client_devices_edit
        form = MyForm(request.form, device)
      File "/usr/local/lib/python2.7/dist-packages/WTForms-2.1-py2.7.egg/wtforms/form.py", line 212, in __call__
        return type.__call__(cls, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/Flask_WTF-0.14.2-py2.7.egg/flask_wtf/form.py", line 158, in __init__
        super(Form, self).__init__(*args, **kwargs)
    TypeError: __init__() takes at most 2 arguments (3 given)
    ERROR:tornado.access:500 GET /client/plugin-weather.vesta/dmg_devices/edit/31 (192.168.0.5) 46.78ms
    --------------------------------------------------------------------------------
    INFO in application [/opt/dmg/domogik/src/domogik/admin/application.py:94]:
    http request for /rest/sensor/158 received
    ...
    

i'm on Debian Strech.

    # pip list |grep -iE "WTF|tornado"
    Flask-WTF (0.14.2)
    tornado (4.4.2)
    WTForms (2.1)
    WTForms-Components (0.10.2)

**Comment by vdomos** [comment]
There are also other issues, plugins appear dead for a few seconds, unable to save configuration plugins ...
This would not be related to the libzmq-dev ?
I had this message to the installation

    Aucune version du paquet **libzmq-dev** n'est disponible, mais il existe dans la base
    de données. Cela signifie en général que le paquet est manquant, qu'il est devenu obsolète
    ou qu'il n'est disponible que sur une autre source
    
    E: Le paquet « libzmq-dev » n'a pas de version susceptible d'être installée
    E: Impossible de trouver le paquet python-gluon
    Something bad happens during command
    You should stop this step to see what is bad
    Continue [Y/n] ?
    Continue [Y/n] ?
    Y
    OK, let's continue...


Lib **libzmq-dev** has changed its name: => libzmq3-dev

    # apt-cache search libzmq
    libjeromq-java - Java implementation of the ZeroMQ messaging library
    libzmq-java - ZeroMQ Java bindings (jzmq)
    libzmq-java-doc - Documentation for ZeroMQ Java bindings (jzmq)
    libzmq-jni - ZeroMQ Java bindings (jzmq)
    libzmq-ffi-perl - version agnostic Perl bindings for zeromq using ffi
    libzmq3-dev - lightweight messaging kernel (development files)
    libzmq5 - lightweight messaging kernel (shared library)
    libzmq5-dbg - lightweight messaging kernel (debugging symbols)

**Comment by cereal2nd** [comment]
this had probably todo with the merge.

can you try to reproduce it with latest

**Comment by vdomos** [comment]
I no longer have the error in "Edit the device"
but another "Internal Server Error" in "Edit the sensor properties"

    [2017-03-25 00:03:51 +0000] [11084] [DEBUG] POST /client/plugin-vdevice.hades/sensors/edit/85
    --------------------------------------------------------------------------------
    INFO in application [/opt/dmg/domogik/src/domogik/admin/application.py:132]:
    http request for /client/plugin-vdevice.hades/sensors/edit/85 received
    --------------------------------------------------------------------------------
    [2017-03-25 00:03:51 +0000] [11084] [ERROR] Error handling request /client/plugin-vdevice.hades/sensors/edit/85
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 135, in handle
        self.handle_request(listener, req, client, addr)
      File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 176, in handle_request
        respiter = self.wsgi(environ, resp.start_response)
      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
        return self.wsgi_app(environ, start_response)
      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/usr/local/lib/python2.7/dist-packages/Flask_Login-0.3.2-py2.7.egg/flask_login.py", line 792, in decorated_view
        return func(*args, **kwargs)
      File "/opt/dmg/domogik/src/domogik/admin/views/clients.py", line 313, in client_sensor_edit
        res = self._db.update_sensor(sensor_id, \
    NameError: global name 'self' is not defined
