### ISSUE TITLE
dmg_cron does not log the erros in /var/log/domogik/core_cron

### ISSUE THREAD

**Issue by fritz-smh** [domogik/domogik#475]
Example in stdout :  
```
root@ambre:/var/log/dansguardian# dmg_cron -h
2017-04-03 13:30:51,141 domogik-core_cron INFO START Cron system run
2017-04-03 13:30:51,152 domogik-core_cron INFO => START device deleting
2017-04-03 13:30:56,916 domogik-core_cron INFO    => Deleting device 'Gorges.OFF2' from plugin 'plugin-weather.ambre'
2017-04-03 13:34:43,061 domogik-core_cron INFO    => Deleting device 'Gorges' from plugin 'plugin-weather.ambre'
2017-04-03 13:34:43,658 domogik-db_api ERROR Can not delete device with id 85, its sensors or commands are used in the following scenarios: Lever de soleil - 15min, Blog - Lever de soleil , Risque
de gel
Traceback (most recent call last):
  File "/usr/local/bin/dmg_cron", line 9, in <module>
    load_entry_point('Domogik==0.6.0', 'console_scripts', 'dmg_cron')()
  File "/opt/dmg/domogik/src/domogik/bin/cron.py", line 68, in main
    cron = CronSystem()
  File "/opt/dmg/domogik/src/domogik/bin/cron.py", line 50, in __init__
    self.run()
  File "/opt/dmg/domogik/src/domogik/bin/cron.py", line 54, in run
    self._delete_devices()
  File "/opt/dmg/domogik/src/domogik/bin/cron.py", line 63, in _delete_devices
    self.db.del_device_real(dev['id'])
  File "/opt/dmg/domogik/src/domogik/common/database.py", line 902, in del_device_real
    self.__raise_dbhelper_exception("Can not delete device with id {0}, its sensors or commands are used in the following scenarios: {1}".format(d_id, ", ".join(tmp)))
  File "/opt/dmg/domogik/src/domogik/common/database.py", line 2136, in __raise_dbhelper_exception
    raise DbHelperException(error_msg)
domogik.common.database.DbHelperException: 'Can not delete device with id 85, its sensors or commands are used in the following scenarios: Lever de soleil - 15min, Blog - Lever de soleil , Risque d
e gel'
```

The error is not in the log file.

**Comment by fritz-smh** [comment]
This is ok now. Closing
