### ISSUE TITLE
Login attempt fail with Docker image

### ISSUE THREAD

**Issue by kubiack** [domogik/domogik#477]
Using the docker image at
[](https://hub.docker.com/r/domogik/domogik/)
And following the indications
```
docker pull domogik/domogik:develop 
docker run -t -i -p 40404:40404 -p 40406:40406 domogik/domogik:develop 
```

I am not able to log in the admin page (error 500 + warning about incorrect login/password).

**Comment by fritz-smh** [comment]
Did you try with the default one ?
admin/123

**Comment by fritz-smh** [comment]
By the way, this make me notice a new port must be opened. See https://github.com/domogik/domogik/issues/478

**Comment by kubiack** [comment]
No, only tried root/domogik and domogik/domogik as per the documentation on dockerhub.

**Comment by fritz-smh** [comment]
The image was broken since a few weeks, I am fixing it.

With the image fixed, there is still the error : 

```
--------------------------------------------------------------------------------
[2017-04-05 20:40:24 +0000] [784] [ERROR] Error handling request /login
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1632, in finalize_request
    response = self.process_response(response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1858, in process_response
    self.save_session(ctx.session, response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 924, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/usr/local/lib/python2.7/dist-packages/Flask_Session-0.3.1-py2.7.egg/flask_session/sessions.py", line 357, in save_session
    session_id = self._get_signer(app).sign(want_bytes(session.sid))
AttributeError: 'NoneType' object has no attribute 'sign'
```

**Comment by fritz-smh** [comment]
related to : https://github.com/domogik/domogik/issues/458

**Comment by fritz-smh** [comment]
New commit pushed... I will check tomorrow if the built image is ok

**Comment by fritz-smh** [comment]
This is fixed. Can you confirm on your side ?

**Comment by kubiack** [comment]
The login admin/123 is working fine on the administration panel (http://localhost:40406).
I understand I tried root/domopass and domogik/domopass but these are for system-side; which the new documentation on docker hub indicates clearly.
Fixed !
Thanks.

**Comment by fritz-smh** [comment]
Cool :)
If you find any other issue, please make a new ticket.
Thanks again for the feedback
