### ISSUE TITLE
500 Error with SensorHistory - Retrieve the history from a certain timestamp 

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#491]
SensorHistory - Retrieve the history between 2 timestamps: OK

    $ curl -s "http://ip:40406/rest/sensorhistory/id/100/from/1495461600/to/1495463014"
    [{"timestamp": 1495461627.0, "value_str": "25.3", "value_num": 25.3}, 
    {"timestamp": 1495461666.0, "value_str": "25.1", "value_num": 25.1}, 
    ...
    {"timestamp": 1495462875.0, "value_str": "25.4", "value_num": 25.4}, 
    {"timestamp": 1495462953.0, "value_str": "25.3", "value_num": 25.3}]

SensorHistory - Retrieve the history from a certain timestamp: KO

    $ curl -s "http://ip:40406/rest/sensorhistory/id/100/from/1495461600"
    <html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>

Same error on Domogik 0.5.3 and 0.6

**Comment by fritz-smh** [comment]
The error :

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/dmg/domogik/src/domogik/admin/application.py", line 169, in create_json_response
    ret = action_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Flask_Login-0.3.2-py2.7.egg/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
  File "/opt/dmg/domogik/src/domogik/admin/rest/sensorhistory.py", line 195, in sensorHistory_from
    return 200, app.db.list_sensor_history_between(sid, ftime)
  File "/opt/dmg/domogik/src/domogik/common/database.py", line 1110, in list_sensor_history_between
    for a_value in self.__session.query(SensorHistory
AttributeError: 'NoneType' object has no attribute 'query'
2017-05-22 17:04:49,699 domogik-admin DEBUG Send client status : alive
```
