### ISSUE TITLE
Internal Server Error in plugin configuration for new plugin

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#514]
In Domogik develop:

New installed plugin or no configuration in database.

    [2017-07-22 18:32:55 +0000] [25259] [INFO] http request for /client/plugin-mysensors.hades/config received
    [2017-07-22 18:32:55 +0000] [25259] [DEBUG] Display configuration for 'plugin-mysensors.hades' :
    [2017-07-22 18:32:55 +0000] [25259] [ERROR] Error handling request /client/plugin-mysensors.hades/config
    Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
    File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
    File "/usr/local/lib/python2.7/dist-packages/Flask_Login-0.3.2-py2.7.egg/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
    File "/opt/dmg/domogik.vdomos/src/domogik/admin/views/clients.py", line 502, in client_config
    app.logger.debug(u"- key='{0}', type='{1}', value='{2}'".format(item["key"], item["type"], item["value"]))
    KeyError: 'value'
    192.168.0.26 - - [22/Jul/2017:18:32:55 +0200] "GET /client/plugin-mysensors.hades/config HTTP/1.1" 500 - "-" "-"
    
    
    [2017-07-22 18:46:47 +0000] [26648] [INFO] http request for /client/plugin-yi.hades/config received
    [2017-07-22 18:46:47 +0000] [26648] [DEBUG] Display configuration for 'plugin-yi.hades' :
    [2017-07-22 18:46:47 +0000] [26648] [ERROR] Error handling request /client/plugin-yi.hades/config
    Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
    File "/usr/local/lib/python2.7/dist-packages/gunicorn-19.7.1-py2.7.egg/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
    File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
    File "/usr/local/lib/python2.7/dist-packages/Flask_Login-0.3.2-py2.7.egg/flask_login.py", line 792, in decorated_view
    return func(*args, **kwargs)
    File "/opt/dmg/domogik.vdomos/src/domogik/admin/views/clients.py", line 502, in client_config
    app.logger.debug(u"- key='{0}', type='{1}', value='{2}'".format(item["key"], item["type"], item["value"]))
    KeyError: 'value'
    192.168.0.26 - - [22/Jul/2017:18:46:47 +0200] "GET /client/plugin-yi.hades/config HTTP/1.1" 500 - "-" "-"

**Comment by vdomos** [comment]
Sorry, I was at the source of the problem
