### ISSUE TITLE
Travis + Rest problem

### ISSUE THREAD

**Issue by overload08** [domogik/domogik#533]
When travis tests creating device, it calls an URL like http://127.0.0.1:40406/rest/device/params/plugin-pluginname.host/pluginname
However, it don't send any json

```
#python 002_create_device.py 
Creating the Hue device...
Getting device_type params hue
Url called is http://127.0.0.1:40406/rest/device/params/plugin-hue.demodomogik/hue
Response : [200] : 
Traceback (most recent call last):
  File "002_create_device.py", line 34, in <module>
    create_device()
  File "002_create_device.py", line 19, in create_device
    params = td.get_params(client_id, "hue")
  File "/opt/dmg/domogik/src/domogik/tests/common/testdevice.py", line 76, in get_params
    params = json.loads(response.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by cereal2nd** [comment]
we don't see this at full travis runs, where are you getting this from?

Do you have an example travis run?
