### ISSUE TITLE
Develop: 500: Internal Server Error in dmg_devices/edit

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#538]
Same error as #458. 

It worked after the fix but it came back when editing Device

    [2017-08-19 09:24:13 +0000] [9660] [DEBUG] GET /client/plugin-rainhour.ares/dmg_devices/edit/8
    [2017-08-19 09:24:13 +0000] [9660] [INFO] http request for /client/plugin-rainhour.ares/dmg_devices/edit/8 received
    [2017-08-19 09:24:13 +0000] [9660] [DEBUG] performance|load_user|{}|0.0641078948975
    [2017-08-19 09:24:13 +0000] [9660] [ERROR] Error handling request /client/plugin-rainhour.ares/dmg_devices/edit/8
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
        self.handle_request(listener, req, client, addr)
      File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
        respiter = self.wsgi(environ, resp.start_response)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__
        return self.wsgi_app(environ, start_response)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
        response = self.handle_exception(e)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
        response = self.full_dispatch_request()
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
        rv = self.dispatch_request()
      File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
        return func(*args, **kwargs)
      File "/home/dan/dmg/domogik/src/domogik/admin/application.py", line 176, in timed
        result = action_func(*args, **kw)
      File "/home/dan/dmg/domogik/src/domogik/admin/views/clients.py", line 455, in client_devices_edit
        form = MyForm(request.form, device)
      File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 212, in __call__
        return type.__call__(cls, *args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/flask_wtf/form.py", line 157, in __init__
        super(Form, self).__init__(*args, **kwargs)
    TypeError: __init__() takes at most 2 arguments (3 given)
    192.168.0.5 - - [19/Aug/2017:09:24:13 +0200] "GET /client/plugin-rainhour.ares/dmg_devices/edit/8 HTTP/1.1" 500 - "-" "-"

**Comment by cereal2nd** [comment]
can you get me the installed version of following packages?
- flask login
- wtforms

**Comment by vdomos** [comment]
On prod VM:
Flask-Login (0.4.0)
Flask-WTF (0.14)
No WTForms

On dev VM:
Flask-WTF (0.10.2)
WTForms (2.0.1)
WTForms-Components (0.10.0)
Flask-Login (0.3.2)

500: Internal Server Error for both

**Comment by tikismoke** [comment]
looks like https://github.com/domogik/domogik/issues/554

Change WTForms version
