### ISSUE TITLE
Issue installing on Debian Stretch 9.3

### ISSUE THREAD

**Issue by sierramike** [domogik/domogik#543]
Hello,

Running the domogik install.py script, it didn't succeed but stopped with the following errors:
 [ Update /etc/default/domogik ]
 [ Trying to find an interface to listen on ]
ERROR:root:Trace: Traceback (most recent call last):
  File "./install.py", line 381, in find_interface
    pkg_resources.get_distribution("domogik").activate()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 553, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 427, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (idna 2.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('idna<2.7,>=2.5'), set(['requests']))

 ==> Trace: Traceback (most recent call last):
  File "./install.py", line 381, in find_interface
    pkg_resources.get_distribution("domogik").activate()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 553, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 427, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 854, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (idna 2.2 (/usr/lib/python2.7/dist-packages), Requirement.parse('idna<2.7,>=2.5'), set(['requests']))

========= TRACEBACK =============
Traceback (most recent call last):
  File "./install.py", line 515, in install
    intf = find_interface()
  File "./install.py", line 392, in find_interface
    return intf
UnboundLocalError: local variable 'intf' referenced before assignment

=================================
ERROR:root:(<type 'exceptions.UnboundLocalError'>, UnboundLocalError("local variable 'intf' referenced before assignment",), <traceback object at 0x7f594a9033f8>)
 ==> (<type 'exceptions.UnboundLocalError'>, UnboundLocalError("local variable 'intf' referenced before assignment",), <traceback object at 0x7f594a9033f8>)
root@srvx-domogik:/opt/dmg/domogik#

Could someone help me identify what's wrong?

Thanks

**Comment by sierramike** [comment]
Hum, is there some support here ? Is this project frozen or abandonned ?

**Comment by cereal2nd** [comment]
The project is alive, but we need to install some VM with Debian to check
what's going on.

But this looks like some conflict in version of the packages.

**Comment by tikismoke** [comment]
Didn't get this error in 9.6 did you install correctly netifaces?

**Comment by Darknet** [comment]
I tries to install on debian 9.3, similar case maybe #556
