### ISSUE TITLE
xplgw crash

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#552]
```
2018-11-04 16:27:22,109 domogik-xplgw INFO Storing stat for device 'nest.thermostat' (423) and sensor 'Last Connection' (2771) with value 'None' after conversion.
2018-11-04 16:27:22,137 domogik-xplgw ERROR Error when adding sensor history : Traceback (most recent call last):
  File "/home/domogik/src/domogik/bin/xplgw.py", line 862, in run
    current_date)
  File "/home/domogik/src/domogik/common/database.py", line 1033, in add_sensor_history
    self.__raise_dbhelper_exception(u"Error when adding data to sensor history. Sensor id = {0}  | Value = {1}  | Date = {2}. Error is {3}".format(sid, value, date, traceback.format_exc()))
  File "/home/domogik/src/domogik/common/database.py", line 1945, in __raise_dbhelper_exception
    raise DbHelperException(error_msg)
DbHelperException: u'Error when adding data to sensor history. Sensor id = 2771  | Value = None  | Date = 1541345175. Error is Traceback (most recent call last):\n  File "/home/domogik/src/domogik/common/database.py", line 952, in add_sensor_history\n    self._do_commit()\n  File "/home/domogik/src/domogik/common/database.py", line 256, in _do_commit\n    self.__raise_dbhelper_exception("SQL exception (commit) : {0}".format(sql_exception))\n  File "/home/domogik/src/domogik/common/database.py", line 1945, in __raise_dbhelper_exception\n    raise DbHelperException(error_msg)\nDbHelperException: \'SQL exception (commit) : (pymysql.err.IntegrityError) (1048, u"Column \\\'value_str\\\' cannot be null") [SQL: u\\\'INSERT INTO core_sensor_history (sensor_id, date, value_num, value_str, original_value_num) VALUES (%(sensor_id)s, %(date)s, %(value_num)s, %(value_str)s, %(original_value_num)s)\\\'] [parameters: {\\\'date\\\': datetime.datetime(2018, 11, 4, 16, 26, 15), \\\'sensor_id\\\': 2771, \\\'original_value_num\\\': None, \\\'value_str\\\': None, \\\'value_num\\\': None}]\'\n'

2018-11-04 16:27:22,228 domogik-xplgw ERROR Traceback (most recent call last):
  File "/home/domogik/src/domogik/bin/xplgw.py", line 870, in run
    self._log.error(u"Error when adding sensor history : {0}".format(traceback.format_exc()))
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/domogik/src/domogik/common/database.py", line 180, in session_scope
    self.__session.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 813, in commit
    self.transaction.commit()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 390, in commit
    self._assert_active(prepared_ok=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 214, in _assert_active
    % self._rollback_exception
InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (pymysql.err.IntegrityError) (1048, u"Column 'value_str' cannot be null") [SQL: u'INSERT INTO core_sensor_history (sensor_id, date, value_num, value_str, original_value_num) VALUES (%(sensor_id)s, %(date)s, %(value_num)s, %(value_str)s, %(original_value_num)s)'] [parameters: {'date': datetime.datetime(2018, 11, 4, 16, 26, 15), 'sensor_id': 2771, 'original_value_num': None, 'value_str': None, 'value_num': None}]


```
See when trying to debug the perpetual crash i had since yesterday

**Comment by tikismoke** [comment]
My problems comes from the hardware.

I have a raid degraded and it slow down MySQL.

But do not know wy these error.

**Comment by jaywax** [comment]
Hello,
Does your sensor still exists (id=2771)?
I've crashed xplgw in the same way when i wanted to update a sensor that hat did not exist anymore.

**Comment by fritz-smh** [comment]
Can you try this patch ?


                              # TODO : commit is done later in the function
                              #self._do_commit()
                      # finally store the value
-                    h = SensorHistory(sensor['id'], 
datetime.datetime.fromtimestamp(date), value, orig_value=orig_value)
+                    h = SensorHistory(sensor['id'], 
datetime.datetime.fromtimestamp(date), value or "", 
orig_value=orig_value or "")
+                    self.__session.add(h)
+                    h = SensorHistory(sensor['id'], 
datetime.datetime.fromtimestamp(date), value or "", 
orig_value=orig_value or "")
                      self.__session.add(h)
                      self._do_commit()
                      if self._cacheDB: 
self._cacheDB.markAsUpdatingDevices(sensor_id=sensor['id'])

**Comment by tikismoke** [comment]
Ok will try this weekend.

Now the raid as finished is rebuild and xplgw queue as success.

So domogik finally beats my raid issue :)
No value lost.

**Comment by tikismoke** [comment]
I haven't been able to reproduce so i close for now as migrating to develop
