### ISSUE TITLE
can't edit device

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#554]
```
==> /var/log/domogik/core_admin_http.log <==
[2018-11-30 10:36:10 +0000] [5262] [DEBUG] GET /client/plugin-onewired.domogik/dmg_devices/edit/54
[2018-11-30 10:36:10 +0000] [5262] [INFO] http request for /client/plugin-onewired.domogik/dmg_devices/edit/54 received
[2018-11-30 10:36:10 +0000] [5262] [DEBUG] performance|load_user|{}|0.00449514389038
[2018-11-30 10:36:10 +0000] [5262] [ERROR] Error handling request /client/plugin-onewired.domogik/dmg_devices/edit/54
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/dmgtest/domogik/src/domogik/admin/application.py", line 176, in timed
    result = action_func(*args, **kw)
  File "/opt/dmgtest/domogik/src/domogik/admin/views/clients.py", line 455, in client_devices_edit
    form = MyForm(request.form, device)
  File "/usr/local/lib/python2.7/dist-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_wtf/form.py", line 157, in __init__
    super(Form, self).__init__(*args, **kwargs)
TypeError: __init__() takes at most 2 arguments (3 given)
192.168.0.68 - - [30/Nov/2018:10:36:10 +0100] "GET /client/plugin-onewired.domogik/dmg_devices/edit/54 HTTP/1.1" 500 - "-" "-"

```

**Comment by Nico0084** [comment]
Work with commit above, but could be reappear with libs upgrade.
So not closed.

**Comment by tikismoke** [comment]
Also a save option make error 500 (will post later the crash)

**Comment by Nico0084** [comment]
I can't reproduce this issue !
Is it for all devices or just 54 ?
Check your lib :

My Libs rev : 

Flask==0.10.1
Flask-Babel==0.10.0
Flask-Bootstrap==3.3.5.7
Flask-Login==0.3.2
Flask-QRcode==1.0
Flask-Session==0.3.0
Flask-WTF==0.12

WTForms==2.1
WTForms-Components==0.10.3

**Comment by tikismoke** [comment]
I'll do this tonight. also an update before :)

Just try at the moment. Can edit but not save.

I'll check libs and update in few minutes.

**Comment by tikismoke** [comment]
Pip freeze show me this:

Flask==0.12
Flask-Babel==0.11.2
Flask-Bcrypt==0.7.1
Flask-Login==0.4.0
Flask-Session==0.3.1
Flask-SocketIO==3.1.0
Flask-Themes==0.1.3
Flask-Themes2==0.1.4
Flask-WTF==0.13.1

WTForms==2.2.1
WTForms-Components==0.10.3


i do some downgrade to those and let you know.

**Comment by tikismoke** [comment]
Still the same in fact i think something as change has change.

I do not remember but now i can't "Save" device when editing. Don't remenber if it was this the problem i'll post the log when it crash :

```
2019-01-09 11:13:36,159 domogik-admin DEBUG Send client status : alive
MQPub > send_event category='plugin.status'
--------------------------------------------------------------------------------
INFO in application [/opt/dmgtest/domogik/src/domogik/admin/application.py:148]:
http request for /client/plugin-script.domogik/dmg_devices/edit/273 received
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
DEBUG in application [/opt/dmgtest/domogik/src/domogik/admin/application.py:178]:
performance|load_user|{}|0.00425815582275
--------------------------------------------------------------------------------


Not really interesting and can't see anything else.
When saving i got an internal error but the device is correctly update :(

```

**Comment by tikismoke** [comment]
Solved by : pip install -r requirements.txt by hand :(
