### ISSUE TITLE
scenario creat issue

### ISSUE THREAD

**Issue by tikismoke** [domogik/domogik#555]
Can't create a new scenario:

```
2019-02-10 18:56:50,495 domogik-scenario INFO Create or save scenario : name = '0', id = '0', json = '{"type":"controls_if","id":"aA=qW-_fPa$3.hNCQkJG","IF0":{"type":"logic_compare","id":"T9PN{}bKKL4sVC$AY5n/","OP":"LT","A":{"type":"sensor.SensorTest.2423","id":"=DU/9df]dBme4P*tYy73","usage.usage":"value"},"B":{"type":"math_number","id":"{D6;itx?(U_tBjlSn=f}","NUM":"31"}},"DO0":{"type":"trigger.Hysteresis","id":"j4X0@sTkSl0,:+{7m`n4","Run":{"type":"command.CommandAction.219","id":"k%@GM8#tejnlC2lO~=*~","body":{"type":"text","id":"aH016-j,%M,_(a*t[o_p","TEXT":"chaudiere en panne."}}}}'
2019-02-10 18:56:50,495 domogik-scenario ERROR Exception occured during message processing.
2019-02-10 18:56:50,497 domogik-scenario DEBUG Traceback (most recent call last):
  File "/opt/dmgtest/domogik/src/domogik/bin/scenario.py", line 111, in on_mdp_request
    payload = mapping[msg.get_action().split('.')[0]][msg.get_action().split('.')[1]](**msg.get_data())
  File "/opt/dmgtest/domogik/src/domogik/scenario/manager.py", line 180, in update_scenario
    return self.create_scenario(name, json_input, cid, dis, desc, behav, state, True)
  File "/opt/dmgtest/domogik/src/domogik/scenario/manager.py", line 227, in create_scenario
    scen = self._db.add_scenario(name, json_input, dis, desc, behavior, False)
  File "/opt/dmgtest/domogik/src/domogik/common/database.py", line 2031, in add_scenario
    scenario = Scenario(name=s_name, json=s_json, disabled=s_disabled, description=s_desc, state=s_state, behavior=s_behavior)
TypeError: __init__() got an unexpected keyword argument 'behavior'

```

**Comment by tikismoke** [comment]
Cool many thank's

Le 25 avril 2019 00:25:46 GMT+02:00, Nico0084 <notifications@github.com> a écrit :
>Closed #555 via 0937d3291fa0d6c65f4186cd02f2ce4f29d0c211.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/domogik/domogik/issues/555#event-2298662207

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
