### ISSUE TITLE
linux newbie ,getting 0MQ when trying to start Domogik

### ISSUE THREAD

**Issue by HLS66** [domogik/domogik#560]
This is the output from terminal.

Starting 0MQ broker ...Traceback (most recent call last):
  File "/usr/local/bin/dmg_broker", line 11, in <module>
    load_entry_point('Domogik-MQ', 'console_scripts', 'dmg_broker')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/dmg/domogik-mq-1.4/src/domogikmq/reqrep/broker.py", line 29, in <module>
    from zmq.eventloop.zmqstream import ZMQStream
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-18.0.2-py2.7-linux-x86_64.egg/zmq/eventloop/__init__.py", line 3, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "/usr/local/lib/python2.7/dist-packages/pyzmq-18.0.2-py2.7-linux-x86_64.egg/zmq/eventloop/ioloop.py", line 20, in <module>
    from tornado.log import gen_log
  File "/usr/local/lib/python2.7/dist-packages/tornado-6.0.3-py2.7-linux-x86_64.egg/tornado/log.py", line 55
    def _stderr_supports_color() -> bool:
                                 ^
SyntaxError: invalid syntax
 An error occured during 0MQ broker startup.

Thanks for your help.

**Comment by tikismoke** [comment]
Hi, what version of the mq are you using?

Add more information in your ticket so dev will have more info to help you.
Version for domogik, Linux, python, install method etc..

**Comment by HLS66** [comment]
Linux mint 19,dmq 1.4,,domogik 0.5, python 2.7.followed instruction for easy install.Did not have any previous versions installed.

**Comment by HLS66** [comment]
Found the problem. Installed domogik on  ubuntu and had the same
issue,after some google searching , found that the issue was with
Tornado,did an uninstall,reinstall,no more 0mq error.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
