### ISSUE TITLE
Error with first dmg_package install

### ISSUE THREAD

**Issue by vdomos** [domogik/domogik#99]
On a fresh installation of Domogik 0.4.1, I have this error when first installing two packages available.
The command has been launched as a user 'Domogik' said the installation.

Debian/Jessie
REST_API_release : 0.7
Domogik_release : 0.4.1
Sources_release : 0.4.1

$  dmg_package --install https://github.com/fritz-smh/domogik-plugin-weather/archive/1.2.zip --hash 615d6de51190110b7edf7339b64471c33d40b34844bfc5ca19eba36a47b5c9fa 
Start downloading https://github.com/fritz-smh/domogik-plugin-weather/archive/1.2.zip
Error while downloading the package : Traceback (most recent call last):
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 356, in download_from_url
    response = requests.get(url, stream=STREAM)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 595, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 189, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 606, in send
    r.content
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 724, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 653, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 851, in _raise_ssl_error
    raise ZeroReturnError()
ZeroReturnError

Download finished
Traceback (most recent call last):
  File "/usr/local/bin/dmg_package", line 9, in <module>
    load_entry_point('Domogik==0.4.0', 'console_scripts', 'dmg_package')()
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 587, in main
    pkg = PackageInstaller()
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 124, in __init__
    self.install(self.options.install, self.options.hash)
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 167, in install
    downloaded_file, mime = self.download_from_url(package)
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 402, in download_from_url
    return downloaded_file, mime
UnboundLocalError: local variable 'mime' referenced before assignment

$ dmg_package --install https://github.com/fritz-smh/domogik-plugin-diskfree/archive/1.3.zip --hash 9be94dee0138e6e7b48ae74bfc587774848495d9d322812be0351d484d5603b4   
Start downloading https://github.com/fritz-smh/domogik-plugin-diskfree/archive/1.3.zip
Error while downloading the package : Traceback (most recent call last):
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 356, in download_from_url
    response = requests.get(url, stream=STREAM)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 595, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 189, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 606, in send
    r.content
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 724, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 653, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 851, in _raise_ssl_error
    raise ZeroReturnError()
ZeroReturnError

Download finished
Traceback (most recent call last):
  File "/usr/local/bin/dmg_package", line 9, in <module>
    load_entry_point('Domogik==0.4.0', 'console_scripts', 'dmg_package')()
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 587, in main
    pkg = PackageInstaller()
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 124, in __init__
    self.install(self.options.install, self.options.hash)
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 167, in install
    downloaded_file, mime = self.download_from_url(package)
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 402, in download_from_url
    return downloaded_file, mime
UnboundLocalError: local variable 'mime' referenced before assignment

**Comment by fritz-smh** [comment]
Can you try using http in the url instead of http to see what happen as the error is related to ssl ?
For now, I will change url on the repo to use http instead of https.

**Comment by vdomos** [comment]
Same error without ssl !

But it's works without "--hash" parameter:

$ dmg_package --install http://github.com/fritz-smh/domogik-plugin-diskfree/archive/1.3.zip
Start downloading http://github.com/fritz-smh/domogik-plugin-diskfree/archive/1.3.zip
Download finished
Upgrade a package from a zip file : /tmp/tmpjeB_Ny
Extract the zip file /tmp/tmpjeB_Ny as /var/lib/domogik/domogik_packages/plugin_diskfree
Generate the docummentation...

Package installed!

FOR NOW, AFTER INSTALLING A PACKAGE, YOU NEED TO RESTART DOMOGIK MANAGER !
To do this, please do : 
sudo /etc/init.d/domogik restart

**Comment by fritz-smh** [comment]
Thanks for the test, I removed the --hash option from the website display until I fix the issue

**Comment by vdomos** [comment]
L'erreur "UnboundLocalError: local variable 'mime' referenced before assignment" lors d'un dmg_package se fait systématiquement au premier lancement, met au 2ième lancement de la commande , cela passe !

La log: 
/var/log/domogik/package.log


2015-10-02 20:37:49,893 domogik-package INFO Start downloading https://github.com/fritz-smh/domogik-plugin-weather/archive/1.2.zip
2015-10-02 20:37:51,584 domogik-package ERROR Error while downloading the package : Traceback (most recent call last):
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 356, in download_from_url
    response = requests.get(url, stream=STREAM)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 595, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 189, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 606, in send
    r.content
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 724, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 653, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 851, in _raise_ssl_error
    raise ZeroReturnError()
ZeroReturnError

2015-10-02 20:37:51,585 domogik-package INFO Download finished
2015-10-02 20:45:21,617 domogik-package INFO Start downloading https://github.com/fritz-smh/domogik-plugin-diskfree/archive/1.3.zip
2015-10-02 20:45:23,076 domogik-package ERROR Error while downloading the package : Traceback (most recent call last):
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 356, in download_from_url
    response = requests.get(url, stream=STREAM)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 595, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 189, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 606, in send
    r.content
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 724, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 653, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 851, in _raise_ssl_error
    raise ZeroReturnError()
ZeroReturnError

2015-10-02 20:45:23,078 domogik-package INFO Download finished
2015-10-03 11:20:00,713 domogik-package INFO Start downloading http://github.com/fritz-smh/domogik-plugin-diskfree/archive/1.3.zip
2015-10-03 11:20:02,827 domogik-package ERROR Error while downloading the package : Traceback (most recent call last):
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 356, in download_from_url
    response = requests.get(url, stream=STREAM)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 595, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 189, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 606, in send
    r.content
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 724, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 653, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 851, in _raise_ssl_error
    raise ZeroReturnError()
ZeroReturnError

2015-10-03 11:20:02,830 domogik-package INFO Download finished
2015-10-03 11:22:40,988 domogik-package INFO Start downloading http://github.com/fritz-smh/domogik-plugin-diskfree/archive/1.3.zip
2015-10-03 11:22:42,882 domogik-package INFO Download finished
2015-10-03 11:22:42,882 domogik-package INFO Upgrade a package from a zip file : /tmp/tmpjeB_Ny
2015-10-03 11:22:42,889 domogik-package INFO Extract the zip file /tmp/tmpjeB_Ny as /var/lib/domogik/domogik_packages/plugin_diskfree
2015-10-03 11:22:42,904 domogik-package INFO Generate the docummentation...
2015-10-03 11:22:44,790 domogik-package INFO 
2015-10-03 11:22:44,790 domogik-package INFO Package installed!
2015-10-03 11:22:44,790 domogik-package INFO 
2015-10-03 11:22:44,790 domogik-package INFO FOR NOW, AFTER INSTALLING A PACKAGE, YOU NEED TO RESTART DOMOGIK MANAGER !
2015-10-03 11:22:44,790 domogik-package INFO To do this, please do : 
2015-10-03 11:22:44,790 domogik-package INFO sudo /etc/init.d/domogik restart
2015-10-03 11:30:18,268 domogik-package INFO Start downloading https://github.com/fritz-smh/domogik-plugin-weather/archive/1.2.zip
2015-10-03 11:30:19,752 domogik-package ERROR Error while downloading the package : Traceback (most recent call last):
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 356, in download_from_url
    response = requests.get(url, stream=STREAM)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 595, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 189, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 606, in send
    r.content
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 724, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 653, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 851, in _raise_ssl_error
    raise ZeroReturnError()
ZeroReturnError

2015-10-03 11:30:19,755 domogik-package INFO Download finished
2015-10-03 11:30:33,191 domogik-package INFO Start downloading http://github.com/fritz-smh/domogik-plugin-weather/archive/1.2.zip
2015-10-03 11:30:34,936 domogik-package INFO Download finished
2015-10-03 11:30:34,936 domogik-package INFO Upgrade a package from a zip file : /tmp/tmpV7yu_W
2015-10-03 11:30:34,943 domogik-package INFO Extract the zip file /tmp/tmpV7yu_W as /var/lib/domogik/domogik_packages/plugin_weather
2015-10-03 11:30:34,949 domogik-package INFO Generate the docummentation...
2015-10-03 11:30:35,303 domogik-package INFO 
2015-10-03 11:30:35,303 domogik-package INFO Package installed!
2015-10-03 11:30:35,303 domogik-package INFO 
2015-10-03 11:30:35,303 domogik-package INFO FOR NOW, AFTER INSTALLING A PACKAGE, YOU NEED TO RESTART DOMOGIK MANAGER !
2015-10-03 11:30:35,303 domogik-package INFO To do this, please do : 
2015-10-03 11:30:35,303 domogik-package INFO sudo /etc/init.d/domogik restart
2015-10-05 10:46:29,473 domogik-package INFO Start downloading http://github.com/fritz-smh/domogik-plugin-rfxcom/archive/1.68.2.zip
2015-10-05 10:46:35,691 domogik-package ERROR Error while downloading the package : Traceback (most recent call last):
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 356, in download_from_url
    response = requests.get(url, stream=STREAM)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 595, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 189, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 606, in send
    r.content
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 724, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 653, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 851, in _raise_ssl_error
    raise ZeroReturnError()
ZeroReturnError

2015-10-05 10:46:35,694 domogik-package INFO Download finished
2015-10-05 10:46:54,148 domogik-package INFO Start downloading http://github.com/fritz-smh/domogik-plugin-rfxcom/archive/1.68.2.zip
2015-10-05 10:47:01,646 domogik-package INFO Download finished
2015-10-05 10:47:01,647 domogik-package INFO Upgrade a package from a zip file : /tmp/tmpSWzEnc
2015-10-05 10:47:01,699 domogik-package INFO Extract the zip file /tmp/tmpSWzEnc as /var/lib/domogik/domogik_packages/plugin_rfxcom
2015-10-05 10:47:01,778 domogik-package INFO Generate the docummentation...
2015-10-05 10:47:04,341 domogik-package INFO 
2015-10-05 10:47:04,341 domogik-package INFO Package installed!
2015-10-05 10:47:04,341 domogik-package INFO 
2015-10-05 10:47:04,341 domogik-package INFO FOR NOW, AFTER INSTALLING A PACKAGE, YOU NEED TO RESTART DOMOGIK MANAGER !
2015-10-05 10:47:04,341 domogik-package INFO To do this, please do : 
2015-10-05 10:47:04,341 domogik-package INFO sudo /etc/init.d/domogik restart
2015-10-05 23:00:02,402 domogik-package INFO Start downloading https://github.com/Cereal2nd/domogik-plugin-onewire/archive/develop.zip
2015-10-05 23:00:04,560 domogik-package ERROR Error while downloading the package : Traceback (most recent call last):
  File "/opt/dmg/domogik-0.4.1/src/domogik/bin/package.py", line 356, in download_from_url
    response = requests.get(url, stream=STREAM)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 595, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 189, in resolve_redirects
    allow_redirects=False,
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 606, in send
    r.content
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 724, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 653, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 256, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python2.7/httplib.py", line 573, in read
    s = self.fp.read(amt)
  File "/usr/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 188, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 995, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 851, in _raise_ssl_error
    raise ZeroReturnError()
ZeroReturnError

2015-10-05 23:00:04,563 domogik-package INFO Download finished
2015-10-05 23:00:11,611 domogik-package INFO Start downloading https://github.com/Cereal2nd/domogik-plugin-onewire/archive/develop.zip
2015-10-05 23:00:13,697 domogik-package INFO Download finished
2015-10-05 23:00:13,698 domogik-package INFO Upgrade a package from a zip file : /tmp/tmpDlfZ4L
2015-10-05 23:00:13,709 domogik-package INFO Extract the zip file /tmp/tmpDlfZ4L as /var/lib/domogik/domogik_packages/plugin_onewire
2015-10-05 23:00:13,731 domogik-package INFO Generate the docummentation...
2015-10-05 23:00:15,473 domogik-package INFO 
2015-10-05 23:00:15,473 domogik-package INFO Package installed!
2015-10-05 23:00:15,473 domogik-package INFO 
2015-10-05 23:00:15,473 domogik-package INFO FOR NOW, AFTER INSTALLING A PACKAGE, YOU NEED TO RESTART DOMOGIK MANAGER !
2015-10-05 23:00:15,473 domogik-package INFO To do this, please do : 
2015-10-05 23:00:15,473 domogik-package INFO sudo /etc/init.d/domogik restart
